const assert=require('assert');const fs=require('fs');const fsp=fs.promises;const os=require('os');const path=require('path');
const {CycleStore}=require('../electron/services/cycle-store.cjs');const {CycleEngine}=require('../electron/services/cycle-engine.cjs');const {TransactionStore}=require('../electron/services/transaction-store.cjs');
const {healthCycle,organizeCycle}=require('../electron/services/file-cycles.cjs');const {missionCycle}=require('../electron/services/workspace-cycles.cjs');
(async()=>{
 const workspace=await fsp.mkdtemp(path.join(os.tmpdir(),'wa-ai-mission-ws-'));const state=await fsp.mkdtemp(path.join(os.tmpdir(),'wa-ai-mission-state-'));await fsp.writeFile(path.join(workspace,'note.txt'),'hello');
 const store=new CycleStore(state),tx=new TransactionStore(state),engine=new CycleEngine({store,maxIterations:40});let outcome=null;
 engine.register('workspace-health',healthCycle());engine.register('organize',organizeCycle({transactionStore:tx}));engine.register('mission',missionCycle({getEngine:()=>engine,onOutcome:(plan,status)=>{outcome={plan,status}}}));
 const goalPlan={schemaVersion:'workspace-ai-goal-plan-v1',text:'[LOCAL_AI_REDACTED_COMMAND]',confidence:.95,constraints:{noArbitraryShell:true,writeRequiresConfirmation:true,interactiveSkillsBlocked:true},notes:[],blocked:[],summary:'AI validated plan',steps:[{id:'ai-step-1',skillId:'skill.workspace.health',type:'workspace-health',label:'Workspace Health',input:{},reason:'read first',requiresConfirmation:false},{id:'ai-step-2',skillId:'skill.file.organize',type:'organize',label:'Safe Organize',input:{mode:'type'},reason:'controlled write',requiresConfirmation:true}]};
 let m=engine.create('mission',{root:workspace,command:'[LOCAL_AI_PLAN]',goalPlan,planSource:'local-ai-token'});m=await engine.run(m.id);assert.equal(m.status,'waiting-confirmation');assert.equal(m.missionDag.summary.write,1);assert.equal(m.goalPlan.text,'[LOCAL_AI_REDACTED_COMMAND]');m=await engine.confirm(m.id,'approve');assert.equal(m.status,'completed');assert.equal(outcome.status,'completed');assert.equal(outcome.plan.schemaVersion,'workspace-ai-goal-plan-v1');assert(fs.existsSync(path.join(workspace,'Documents','note.txt'))||fs.existsSync(path.join(workspace,'Text','note.txt'))||!fs.existsSync(path.join(workspace,'note.txt')));
 await fsp.rm(workspace,{recursive:true,force:true});await fsp.rm(state,{recursive:true,force:true});console.log('ai-mission-v090.test.cjs PASS',{children:m.childCycles.length,status:m.status});
})().catch(e=>{console.error(e);process.exit(1)});
