const assert=require('assert');const fs=require('fs');const fsp=fs.promises;const path=require('path');const os=require('os');
const {ExplorerBatchStore}=require('../electron/services/explorer-batch-store.cjs');
const {buildBatchManifest,processBatchChunk,undoBatch}=require('../electron/services/explorer-batch-service.cjs');
(async()=>{const base=await fsp.mkdtemp(path.join(os.tmpdir(),'wa-v095-recovery-')),root=path.join(base,'ws');await fsp.mkdir(path.join(root,'dest'),{recursive:true});const store=new ExplorerBatchStore(base);
 // simulate crash after destination backup, before stage commit
 await fsp.writeFile(path.join(root,'r.txt'),'NEW');await fsp.writeFile(path.join(root,'dest','r.txt'),'OLD');let plan=await buildBatchManifest({root,operation:'copy',sourcesRelative:['r.txt'],destinationDirRelative:'dest',conflictPolicy:'replace',duplicateAware:false});let job=store.createJob({id:'j1',root,operation:'copy',destinationDir:plan.destinationDir,conflictPolicy:'replace',duplicateAware:false,items:plan.items});let item=store.item('j1',0);const art=path.join(root,'.workspace-agent-batch','j1'),stage=path.join(art,'stage','0.part'),backup=path.join(art,'backup','0-r.txt');await fsp.mkdir(path.dirname(stage),{recursive:true});await fsp.mkdir(path.dirname(backup),{recursive:true});await fsp.copyFile(item.source,stage);await fsp.rename(item.destination,backup);store.updateItem('j1',0,{state:'backed-up',stagePath:stage,backupPath:backup});let out=await processBatchChunk(store,'j1',{limit:2});assert.equal(out.status,'completed');assert.equal(await fsp.readFile(path.join(root,'dest','r.txt'),'utf8'),'NEW');let undo=await undoBatch(store,'j1');assert(undo.every(x=>x.ok));assert.equal(await fsp.readFile(path.join(root,'dest','r.txt'),'utf8'),'OLD');
 // simulate crash after commit before item marked done
 await fsp.writeFile(path.join(root,'c.txt'),'NEW2');await fsp.writeFile(path.join(root,'dest','c.txt'),'OLD2');plan=await buildBatchManifest({root,operation:'copy',sourcesRelative:['c.txt'],destinationDirRelative:'dest',conflictPolicy:'replace',duplicateAware:false});store.createJob({id:'j2',root,operation:'copy',destinationDir:plan.destinationDir,conflictPolicy:'replace',duplicateAware:false,items:plan.items});item=store.item('j2',0);const art2=path.join(root,'.workspace-agent-batch','j2'),backup2=path.join(art2,'backup','0-c.txt');await fsp.mkdir(path.dirname(backup2),{recursive:true});await fsp.rename(item.destination,backup2);await fsp.copyFile(item.source,item.destination);store.updateItem('j2',0,{state:'committed',backupPath:backup2});out=await processBatchChunk(store,'j2',{limit:2});assert.equal(out.status,'completed');undo=await undoBatch(store,'j2');assert(undo.every(x=>x.ok));assert.equal(await fsp.readFile(path.join(root,'dest','c.txt'),'utf8'),'OLD2');
 store.close();await fsp.rm(base,{recursive:true,force:true});console.log('explorer-batch-recovery-v095.test.cjs PASS',{backedUpResume:true,committedResume:true});})().catch(e=>{console.error(e);process.exit(1)});
