const assert=require('assert');
const fs=require('fs');const fsp=fs.promises;const path=require('path');const os=require('os');
const {ExplorerBatchStore}=require('../electron/services/explorer-batch-store.cjs');
const {buildBatchManifest,processBatchChunk,undoBatch}=require('../electron/services/explorer-batch-service.cjs');
const {assertFreeSpace,classifyIoError}=require('../electron/services/explorer-storage-guard.cjs');
async function write(p,text){await fsp.mkdir(path.dirname(p),{recursive:true});await fsp.writeFile(p,text);}
async function runJob(store,id,opts={}){let r;for(let i=0;i<100;i++){r=await processBatchChunk(store,id,{limit:3,...opts});if(r.status==='completed'||r.status==='failed'||r.status==='cancelled'||r.blocker)return r;}throw new Error('job loop exceeded');}
(async()=>{
 const base=await fsp.mkdtemp(path.join(os.tmpdir(),'wa-v096-')),srcRoot=path.join(base,'src-root'),dstRoot=path.join(base,'dst-root');await fsp.mkdir(srcRoot,{recursive:true});await fsp.mkdir(dstRoot,{recursive:true});await fsp.mkdir(path.join(dstRoot,'out'));await fsp.mkdir(path.join(srcRoot,'out'));
 await write(path.join(srcRoot,'tree','a.txt'),'alpha');await write(path.join(srcRoot,'tree','nested','b.txt'),'beta');
 const fakeVolume=async p=>String(p).startsWith(srcRoot)?'volume:SOURCE':'volume:DEST';const fakeStorage=async(root,required,{reserveBytes}={})=>({ok:true,root,freeBytes:10**12,totalBytes:2*10**12,requiredBytes:required,reserveBytes:reserveBytes||0});
 const plan=await buildBatchManifest({sourceRoot:srcRoot,destinationRoot:dstRoot,operation:'move',sourcesRelative:['tree'],destinationDirRelative:'out',conflictPolicy:'rename',volumeIdentityFn:fakeVolume,storageCheck:fakeStorage,reserveBytes:16*1024*1024});assert.equal(plan.crossVolume,true);assert(plan.items.some(x=>x.kind==='file-xmove'));assert(plan.items.some(x=>x.kind==='rmdir-source'));assert(plan.requiredBytes>=9);
 const store=new ExplorerBatchStore(base);store.createJob({id:'cross',root:srcRoot,sourceRoot:srcRoot,destinationRoot:dstRoot,sourceIdentity:'volume:SOURCE',destinationIdentity:'volume:DEST',operation:'move',destinationDir:plan.destinationDir,conflictPolicy:'rename',duplicateAware:true,reserveBytes:16*1024*1024,crossVolume:true,items:plan.items});let r;for(let i=0;i<50;i++){r=await processBatchChunk(store,'cross',{limit:2,rootGate:async()=>({ok:true})});if(r.status==='completed')break;}assert.equal(r.status,'completed');assert(!fs.existsSync(path.join(srcRoot,'tree')));assert.equal(await fsp.readFile(path.join(dstRoot,'out','tree','nested','b.txt'),'utf8'),'beta');const undo=await undoBatch(store,'cross');assert(undo.every(x=>x.ok!==false));assert.equal(await fsp.readFile(path.join(srcRoot,'tree','a.txt'),'utf8'),'alpha');assert(!fs.existsSync(path.join(dstRoot,'out','tree')));

 // cross-volume crash recovery: committed destination + source still present must finish source removal on resume
 await write(path.join(srcRoot,'crash.txt'),'crash-safe');await write(path.join(dstRoot,'out','crash.txt'),'crash-safe');const crashPlan=await buildBatchManifest({sourceRoot:srcRoot,destinationRoot:dstRoot,operation:'move',sourcesRelative:['crash.txt'],destinationDirRelative:'out',conflictPolicy:'replace',duplicateAware:false,volumeIdentityFn:fakeVolume,storageCheck:fakeStorage,reserveBytes:16*1024*1024});store.createJob({id:'xcrash',root:srcRoot,sourceRoot:srcRoot,destinationRoot:dstRoot,sourceIdentity:'volume:SOURCE',destinationIdentity:'volume:DEST',operation:'move',destinationDir:crashPlan.destinationDir,conflictPolicy:'replace',duplicateAware:false,reserveBytes:16*1024*1024,crossVolume:true,items:crashPlan.items});const xi=store.item('xcrash',0);store.updateItem('xcrash',0,{state:'committed',destinationHash:require('crypto').createHash('sha256').update('crash-safe').digest('hex'),...(process.platform==='win32'?{meta:{ntfsMetadata:await require('../electron/services/windows-ntfs-metadata.cjs').preserveWindowsMetadata(path.join(srcRoot,'crash.txt'),path.join(dstRoot,'out','crash.txt'))}}:{})});r=await runJob(store,'xcrash',{rootGate:async()=>({ok:true})});assert.equal(r.status,'completed');assert(!fs.existsSync(path.join(srcRoot,'crash.txt')));assert.equal(await fsp.readFile(path.join(dstRoot,'out','crash.txt'),'utf8'),'crash-safe');
 // low-space preview helper and recoverable classification
 await assert.rejects(()=>assertFreeSpace(dstRoot,1000,{reserveBytes:16*1024*1024,statfs:async()=>({bsize:4096,bavail:1,blocks:100})}),e=>e.code==='EXPLORER_BATCH_INSUFFICIENT_SPACE');assert.equal(classifyIoError({code:'ENOSPC'}).category,'storage');assert.equal(classifyIoError({code:'EROFS'}).category,'permission');
 // disk-full style pause after Preview: inflate reserve after job creation, then reduce and resume
 await write(path.join(srcRoot,'space.txt'),'space');const p2=await buildBatchManifest({root:srcRoot,operation:'copy',sourcesRelative:['space.txt'],destinationDirRelative:'out',conflictPolicy:'rename',storageCheck:fakeStorage,reserveBytes:16*1024*1024});store.createJob({id:'space',root:srcRoot,sourceRoot:srcRoot,destinationRoot:srcRoot,operation:'copy',destinationDir:p2.destinationDir,conflictPolicy:'rename',duplicateAware:true,reserveBytes:16*1024*1024,items:p2.items});store.db.prepare('UPDATE jobs SET reserve_bytes=? WHERE id=?').run(Number.MAX_SAFE_INTEGER,'space');r=await processBatchChunk(store,'space',{limit:2});assert.equal(r.status,'paused');assert.equal(r.blocker.category,'storage');store.db.prepare('UPDATE jobs SET reserve_bytes=? WHERE id=?').run(16*1024*1024,'space');r=await runJob(store,'space');assert.equal(r.status,'completed');
 // root disconnect/identity blocker is checkpointed, not failed
 await write(path.join(srcRoot,'disconnect.txt'),'d');const p3=await buildBatchManifest({root:srcRoot,operation:'copy',sourcesRelative:['disconnect.txt'],destinationDirRelative:'out',conflictPolicy:'rename',storageCheck:fakeStorage,reserveBytes:16*1024*1024});store.createJob({id:'disconnect',root:srcRoot,sourceRoot:srcRoot,destinationRoot:srcRoot,sourceIdentity:'volume:S',destinationIdentity:'volume:S',operation:'copy',destinationDir:p3.destinationDir,conflictPolicy:'rename',duplicateAware:true,reserveBytes:16*1024*1024,items:p3.items});let calls=0;r=await processBatchChunk(store,'disconnect',{rootGate:async()=>++calls===1?{ok:true}:{ok:false,code:'EXPLORER_BATCH_ROOT_IDENTITY_CHANGED',message:'changed'}});assert.equal(r.status,'paused');assert.equal(r.blocker.category,'root');r=await runJob(store,'disconnect',{rootGate:async()=>({ok:true})});assert.equal(r.status,'completed');
 // permission blocker is resumable
 await write(path.join(srcRoot,'perm.txt'),'p');const p4=await buildBatchManifest({root:srcRoot,operation:'copy',sourcesRelative:['perm.txt'],destinationDirRelative:'out',conflictPolicy:'rename',storageCheck:fakeStorage,reserveBytes:16*1024*1024});store.createJob({id:'perm',root:srcRoot,sourceRoot:srcRoot,destinationRoot:srcRoot,operation:'copy',destinationDir:p4.destinationDir,conflictPolicy:'rename',duplicateAware:true,reserveBytes:16*1024*1024,items:p4.items});r=await processBatchChunk(store,'perm',{rootGate:async()=>({ok:false,code:'EXPLORER_BATCH_PERMISSION_PREFLIGHT_FAILED',message:'read-only'})});assert.equal(r.status,'paused');assert.equal(r.blocker.category,'permission');
 store.close();await fsp.rm(base,{recursive:true,force:true});console.log('file-explorer-production-v096.test.cjs PASS',{crossVolume:true,spacePause:true,rootPause:true,permissionPause:true});
})().catch(e=>{console.error(e);process.exit(1)});
