const assert=require('assert');
const os=require('os');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const {scanTree}=require('../electron/services/file-indexer.cjs');
const {findExactDuplicates}=require('../electron/services/duplicate-finder.cjs');
const {buildDuplicateReviewPlan,executeQuarantine,verifyQuarantine,restoreQuarantine}=require('../electron/services/quarantine.cjs');
const {planOrganization,executeMoves,verifyMoves,undoMoves}=require('../electron/services/organizer.cjs');
const {analyzeWorkspace}=require('../electron/services/file-analyzer.cjs');
(async()=>{
  const root=await fsp.mkdtemp(path.join(os.tmpdir(),'wa-guardian-'));
  await fsp.writeFile(path.join(root,'photo.jpg'),'same-content');
  await fsp.writeFile(path.join(root,'photo copy.jpg'),'same-content');
  await fsp.writeFile(path.join(root,'notes.txt'),'hello');
  await fsp.writeFile(path.join(root,'cache.tmp'),'temporary');
  await fsp.mkdir(path.join(root,'empty-folder'));
  const scan=await scanTree(root);
  assert.equal(scan.files.length,4);
  const dups=await findExactDuplicates(scan.files);
  assert.equal(dups.groups.length,1);
  const plan=buildDuplicateReviewPlan(root,dups.groups);
  assert.equal(plan.operations.length,1);
  const q=await executeQuarantine(root,'test-cycle',plan.operations);
  const qv=await verifyQuarantine(q.completed);
  assert.equal(qv.ok,true);
  assert.equal(q.completed.length,1);
  const restored=await restoreQuarantine(q.completed);
  assert.equal(restored.every(x=>x.ok),true);
  const scan2=await scanTree(root);
  const health=await analyzeWorkspace(root,scan2,{largeThresholdBytes:1});
  assert.ok(health.junk.some(x=>x.name==='cache.tmp'));
  assert.ok(health.emptyFolders.some(x=>x.endsWith('empty-folder')));
  const moves=planOrganization(root,scan2.files,{mode:'type'});
  assert.ok(moves.length>=4);
  const done=await executeMoves(moves);
  const mv=await verifyMoves(done);assert.equal(mv.ok,true);
  const undone=await undoMoves(done);assert.equal(undone.every(x=>x.ok),true);
  console.log('file-guardian.test: OK');
})().catch(e=>{console.error(e);process.exit(1)});
