const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const cp=require('child_process');const crypto=require('crypto');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-manual-strength-'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
try{
  const source='1'.repeat(64),lock='2'.repeat(64),rid='3'.repeat(64),installer='4'.repeat(64),evidenceId='5'.repeat(64),executionId='exec-manual-strength',now=new Date().toISOString();
  const manifest=path.join(tmp,'release-manifest.json');fs.writeFileSync(manifest,JSON.stringify({sourceFingerprint:source,packageLockSha256:lock,releaseIdentitySha256:rid,artifacts:[{kind:'nsis',sha256:installer,file:'setup.exe'}]}));
  const primary=path.join(tmp,'primary.json');fs.writeFileSync(primary,JSON.stringify({overall:'PASS',evidenceId,windowsFamily:'Windows10',sourceFingerprint:{sha256:source},packageLockSha256:lock,releaseIdentitySha256:rid}));
  const keys=['physicalUsbDisconnectReconnect','actualDiskFullRecovery','realAclReadOnlyRecovery','uncleanShutdownPowerLoss','realUpgradeFrom0_9_8'];const evidence={};for(const key of keys){const name=`${key}.txt`,p=path.join(tmp,name);fs.writeFileSync(p,`independent evidence bytes for ${key}`);evidence[key]={status:'PASS',observedAt:now,notes:'Hash-bound observed evidence.',attachment:name,attachmentSha256:sha(p),attachmentBytes:fs.statSync(p).size}}
  evidence.realUpgradeFrom0_9_8={...evidence.realUpgradeFrom0_9_8,fromVersion:'0.9.8',toVersion:'1.0.0-rc1',installerSha256:installer,preSelfCheckOverall:'pass',postSelfCheckOverall:'pass',statePreserved:true};
  const doc={schemaVersion:'workspace-agent-manual-evidence-rc1-v4',version:'1.0.0-rc1',executionId,operator:'operator',machine:'WIN-CERT',createdAt:now,binding:{sourceFingerprint:source,packageLockSha256:lock,releaseIdentitySha256:rid,releaseManifestSha256:sha(manifest),installerSha256:installer,primaryCertificationReportSha256:sha(primary),primaryCertificationEvidenceId:evidenceId,primaryWindowsFamily:'Windows10'},evidence};const file=path.join(tmp,'manual.json');fs.writeFileSync(file,JSON.stringify(doc));
  const args=['scripts/verify-manual-evidence-rc1.cjs',file,'--require-all','--require-artifact-binding',`--release-manifest=${manifest}`,`--primary-report=${primary}`,`--execution-id=${executionId}`];let r=cp.spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);
  const saved=evidence.uncleanShutdownPowerLoss;evidence.uncleanShutdownPowerLoss={...saved,attachment:'',attachmentSha256:'',attachmentBytes:0};fs.writeFileSync(file,JSON.stringify(doc));r=cp.spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});assert.notEqual(r.status,0);assert(r.stderr.includes('MANUAL_EVIDENCE_ATTACHMENT_REQUIRED'));evidence.uncleanShutdownPowerLoss=saved;
  doc.binding.primaryCertificationReportSha256='6'.repeat(64);fs.writeFileSync(file,JSON.stringify(doc));r=cp.spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});assert.notEqual(r.status,0);assert(r.stderr.includes('MANUAL_EVIDENCE_PRIMARY_REPORT_BINDING_MISMATCH'));
  console.log('manual-evidence-strength-rc1 PASS',{allFiveAttachmentsRequired:true,primaryReportBound:true});
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
