const assert=require('assert');const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const {exactArtifactNames,validateArtifactRows,liveAuthenticode}=require('../scripts/verify-release-manifest-rc1.cjs');
const names=exactArtifactNames(pkg);assert.equal(names.nsis,'Workspace-Agent-Setup-1.0.0-rc1-x64.exe');assert.equal(names.portable,'Workspace-Agent-Portable-1.0.0-rc1-x64.exe');
const manifest={artifacts:[{kind:'nsis',arch:'x64',file:names.nsis,bytes:1,sha256:'a'.repeat(64)},{kind:'portable',arch:'x64',file:names.portable,bytes:1,sha256:'b'.repeat(64)}],signatures:[{file:names.nsis,status:'Valid'},{file:names.portable,status:'Valid'}]};
let r=validateArtifactRows({pkg,manifest,manifestDir:root,requireSigning:true,readFileMeta:false});assert(r.ok,r.errors.join(','));
r=validateArtifactRows({pkg,manifest:{...manifest,artifacts:manifest.artifacts.slice(0,1)},manifestDir:root,readFileMeta:false});assert(!r.ok&&r.errors.some(x=>x.startsWith('ARTIFACT_PORTABLE_COUNT')));
r=validateArtifactRows({pkg,manifest:{...manifest,signatures:[{file:names.nsis,status:'Valid'},{file:names.portable,status:'NotSigned'}]},manifestDir:root,requireSigning:true,readFileMeta:false});assert(!r.ok&&r.errors.some(x=>x.startsWith('SIGNATURE_INVALID')));
r=validateArtifactRows({pkg,manifest:{...manifest,artifacts:[...manifest.artifacts,{kind:'extra',arch:'x64',file:'unexpected.exe',bytes:1,sha256:'c'.repeat(64)}]},manifestDir:root,readFileMeta:false});assert(!r.ok&&r.errors.some(x=>x.startsWith('ARTIFACT_TOTAL_COUNT'))&&r.errors.some(x=>x.startsWith('ARTIFACT_UNEXPECTED')));
if(process.platform!=='win32'){const live=liveAuthenticode('/tmp/not-used.exe');assert.equal(live.ok,false);assert.equal(live.error,'WINDOWS_REQUIRED');}
const verifierSource=fs.readFileSync(path.join(root,'scripts','verify-release-manifest-rc1.cjs'),'utf8');assert(verifierSource.includes('AUTHENTICODE_LIVE_RECHECK_WINDOWS_REQUIRED'));assert(verifierSource.includes('AUTHENTICODE_THUMBPRINT_MISMATCH'));
const cert=fs.readFileSync(path.join(root,'scripts','windows-certification-v097.ps1'),'utf8');for(const token of ['workspace-agent-release-v10','release-manifest-contract','Workspace-Agent-Setup-$($pkg.version)-x64.exe','Workspace-Agent-Portable-$($pkg.version)-x64.exe','SHA256SUMS.txt'])assert(cert.includes(token),`missing artifact lane invariant: ${token}`);
assert(cert.indexOf("Run-NpmGate 'check:release-inputs'")<cert.indexOf("source-fingerprint.json"),'source fingerprint must be captured after lockfile resolution');
const orchestrator=fs.readFileSync(path.join(root,'scripts','windows-rc1-certify.ps1'),'utf8');assert(orchestrator.includes('--release-manifest=$releaseManifest'));assert(orchestrator.includes('release-manifest.snapshot.json'));assert(orchestrator.includes('peer-windows-evidence'));assert(orchestrator.includes('certificationEvidenceBundle'));assert(orchestrator.includes('workspace-agent-rc1-certification-kit-result-v4'));
console.log('rc1-release-artifact-contract.test.cjs PASS',{nsis:true,portable:true,manifestV10:true,snapshots:true,liveAuthenticodeRecheck:true});
