const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const cp=require('child_process');const crypto=require('crypto');
const root=path.resolve(__dirname,'..');const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-manual-prefill-'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
try{
  const hash='a'.repeat(64),source='b'.repeat(64),lock='c'.repeat(64),rid='d'.repeat(64),evidenceId='e'.repeat(64);const manifest=path.join(tmp,'release-manifest.json'),primary=path.join(tmp,'primary-report.json'),out=path.join(tmp,'manual.json'),executionId='exec-20260816-win11';
  fs.writeFileSync(manifest,JSON.stringify({schemaVersion:'workspace-agent-release-v10',version:'1.0.0-rc1',toolingRevision:'cert-kit21',sourceFingerprint:source,packageLockSha256:lock,releaseIdentitySha256:rid,artifacts:[{kind:'nsis',file:'Workspace-Agent-Setup-1.0.0-rc1-x64.exe',sha256:hash,bytes:123}]}));
  fs.writeFileSync(primary,JSON.stringify({overall:'PASS',evidenceId,windowsFamily:'Windows11',sourceFingerprint:{sha256:source},packageLockSha256:lock,releaseIdentitySha256:rid}));
  const r=cp.spawnSync(process.execPath,['scripts/prefill-manual-evidence-rc1.cjs',`--release-manifest=${manifest}`,`--primary-report=${primary}`,`--out=${out}`,`--execution-id=${executionId}`,'--operator=Test Operator','--machine=WIN-TEST'],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr||r.stdout);
  const d=JSON.parse(fs.readFileSync(out,'utf8'));assert.equal(d.schemaVersion,'workspace-agent-manual-evidence-rc1-v4');assert.equal(d.executionId,executionId);assert.equal(d.operator,'Test Operator');assert.equal(d.machine,'WIN-TEST');assert.equal(d.binding.sourceFingerprint,source);assert.equal(d.binding.packageLockSha256,lock);assert.equal(d.binding.releaseIdentitySha256,rid);assert.equal(d.binding.primaryCertificationReportSha256,sha(primary));assert.equal(d.binding.primaryCertificationEvidenceId,evidenceId);assert.equal(d.binding.primaryWindowsFamily,'Windows11');assert.equal(d.evidence.realUpgradeFrom0_9_8.status,'PENDING_MANUAL');assert(d.prefill.note.includes('Do not reuse'));
  const missing=cp.spawnSync(process.execPath,['scripts/prefill-manual-evidence-rc1.cjs',`--release-manifest=${manifest}`,`--out=${path.join(tmp,'missing.json')}`,`--execution-id=${executionId}`],{cwd:root,encoding:'utf8'});assert.notEqual(missing.status,0);assert((missing.stderr||'').includes('PRIMARY_CERTIFICATION_REPORT_REQUIRED'));
  console.log('rc1-manual-evidence-prefill PASS',{schema:'v4',primaryReportBound:true});
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
