const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const crypto=require('crypto');
const root=path.resolve(__dirname,'..');const {computeFingerprint}=require('../scripts/source-tree-fingerprint.cjs');const {computeReleaseIdentity}=require('../scripts/release-identity.cjs');const {validatePolicy}=require('../scripts/dependency-source-policy.cjs');const {validate:validateStablePolicy}=require('../scripts/stable-certification-policy.cjs');const {createBundle}=require('../scripts/certification-evidence-bundle.cjs');const {reverifyLeafEvidence}=require('../scripts/rc1-stable-readiness.cjs');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')),lockPath=path.join(root,'package-lock.json'),had=fs.existsSync(lockPath),old=had?fs.readFileSync(lockPath):null,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-leaf-reverify-'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const meta=p=>({path:p,bytes:fs.statSync(p).size,sha256:sha(p)});
try{
 const rootLock={name:pkg.name,version:pkg.version,lockfileVersion:3,requires:true,packages:{'':{name:pkg.name,version:pkg.version}}};fs.writeFileSync(lockPath,JSON.stringify(rootLock,null,2));
 const release=path.join(tmp,'release');fs.mkdirSync(release);const nsis=path.join(release,`Workspace-Agent-Setup-${pkg.version}-x64.exe`),portable=path.join(release,`Workspace-Agent-Portable-${pkg.version}-x64.exe`);fs.writeFileSync(nsis,'nsis-bytes');fs.writeFileSync(portable,'portable-bytes');const fp=computeFingerprint(root),rid=computeReleaseIdentity(root),pv=validatePolicy(pkg),sp=validateStablePolicy(pkg);assert(pv.ok);assert(sp.ok);
 const artifacts=[{kind:'nsis',arch:'x64',file:path.basename(nsis),bytes:fs.statSync(nsis).size,sha256:sha(nsis)},{kind:'portable',arch:'x64',file:path.basename(portable),bytes:fs.statSync(portable).size,sha256:sha(portable)}],thumb='B'.repeat(40);const manifest={schemaVersion:'workspace-agent-release-v10',version:pkg.version,toolingRevision:'cert-kit21',featureFreeze:true,createdAt:new Date().toISOString(),packageLockSha256:sha(lockPath),sourceFingerprint:fp.sha256,sourceFiles:fp.files,releaseIdentitySha256:rid.releaseIdentitySha256,dependencySourcePolicy:pv.policy,dependencySourcePolicySha256:pv.sha256,stableCertificationPolicy:sp.policy,stableCertificationPolicySha256:sp.sha256,resolvedRegistryOrigins:[],scaleMatrix:sp.policy.requiredScaleMatrix,architecture:'x64',signingRequired:true,artifacts,signatures:artifacts.map(x=>({file:x.file,status:'Valid',subject:'CN=Fixture',thumbprint:thumb}))};const manifestPath=path.join(release,'release-manifest.json');fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(release,'SHA256SUMS.txt'),artifacts.map(x=>`${x.sha256}  ${x.file}`).join('\n')+'\n');
 const executionId='exec-leaf-test',evidenceId='c'.repeat(64),primaryReport=path.join(tmp,'primary-report.json');fs.writeFileSync(primaryReport,JSON.stringify({overall:'PASS',evidenceId,windowsFamily:'Windows10',sourceFingerprint:{sha256:fp.sha256},packageLockSha256:sha(lockPath),releaseIdentitySha256:rid.releaseIdentitySha256}));
 const manualDir=path.join(tmp,'manual');fs.mkdirSync(manualDir);const now=new Date().toISOString(),evidence={};for(const key of sp.policy.requiredManualEvidenceKeys){const name=`${key}.txt`,p=path.join(manualDir,name);fs.writeFileSync(p,`proof bytes ${key}`);evidence[key]={status:'PASS',observedAt:now,notes:'Observed on certification hardware.',attachment:name,attachmentSha256:sha(p),attachmentBytes:fs.statSync(p).size}}evidence.realUpgradeFrom0_9_8={...evidence.realUpgradeFrom0_9_8,fromVersion:'0.9.8',toVersion:pkg.version,installerSha256:artifacts[0].sha256,preSelfCheckOverall:'pass',postSelfCheckOverall:'pass',statePreserved:true};const manual={schemaVersion:'workspace-agent-manual-evidence-rc1-v4',version:pkg.version,executionId,operator:'tester',machine:'machine',createdAt:now,binding:{sourceFingerprint:fp.sha256,packageLockSha256:sha(lockPath),releaseIdentitySha256:rid.releaseIdentitySha256,releaseManifestSha256:sha(manifestPath),installerSha256:artifacts[0].sha256,primaryCertificationReportSha256:sha(primaryReport),primaryCertificationEvidenceId:evidenceId,primaryWindowsFamily:'Windows10'},evidence};const manualPath=path.join(manualDir,'MANUAL_EVIDENCE.json');fs.writeFileSync(manualPath,JSON.stringify(manual,null,2));
 const pSession=path.join(tmp,'primary-session'),qSession=path.join(tmp,'peer-session');fs.mkdirSync(pSession);fs.mkdirSync(qSession);fs.writeFileSync(path.join(pSession,'gate.log'),'primary');fs.writeFileSync(path.join(qSession,'gate.log'),'peer');const pb=createBundle(pSession,path.join(pSession,'evidence-bundle.json')),qb=createBundle(qSession,path.join(qSession,'evidence-bundle.json'));
 const verdict={executionId,signingRequired:false,inputs:{releaseManifest:meta(manifestPath),manualEvidence:meta(manualPath),artifactReport:meta(primaryReport),artifactEvidenceBundle:meta(pb.path),peerEvidenceBundle:meta(qb.path)}};
 let r=reverifyLeafEvidence(verdict);assert(r.ok,r.errors.join('\n'));
 fs.appendFileSync(nsis,'tamper');r=reverifyLeafEvidence(verdict);assert(!r.ok&&r.errors.some(x=>x.startsWith('LEAF_RELEASE_MANIFEST_REVERIFY_FAILED')));fs.writeFileSync(nsis,'nsis-bytes');
 const attachment=path.join(manualDir,'uncleanShutdownPowerLoss.txt');fs.appendFileSync(attachment,'tamper');r=reverifyLeafEvidence(verdict);assert(!r.ok&&r.errors.some(x=>x.startsWith('LEAF_MANUAL_EVIDENCE_REVERIFY_FAILED')));
 console.log('rc1-promotion-leaf-reverification PASS',{artifactTamperBlocked:true,allManualAttachmentsReverified:true,primaryReportBound:true,evidenceBundlesReverified:true});
}finally{fs.rmSync(tmp,{recursive:true,force:true});if(had)fs.writeFileSync(lockPath,old);else fs.rmSync(lockPath,{force:true})}
