const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
const root=path.resolve(__dirname,'..');const {createHandoff,verifyHandoff}=require('../scripts/rc1-execution-handoff.cjs');
const lock=path.join(root,'package-lock.json'),had=fs.existsSync(lock),old=had?fs.readFileSync(lock):null,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-handoff-link-')),outside=fs.mkdtempSync(path.join(os.tmpdir(),'wa-handoff-out-'));
try{
  if(!had)fs.writeFileSync(lock,JSON.stringify({name:'windows-workspace-agent',version:'1.0.0-rc1',lockfileVersion:3,packages:{}}));
  fs.writeFileSync(path.join(tmp,'payload.txt'),'inside\n');fs.copyFileSync(lock,path.join(tmp,'package-lock.json'));const pointer=path.join(tmp,'primary-pointer.json');fs.writeFileSync(pointer,JSON.stringify({schemaVersion:'workspace-agent-rc1-primary-pointer-v1',executionId:'exec-link',certificationReport:'payload.txt',evidenceBundle:'payload.txt',releaseManifest:'payload.txt',sha256Sums:'payload.txt',manualEvidenceTemplate:'payload.txt',packageLock:'package-lock.json'}));const manifest=path.join(tmp,'handoff-manifest.json');createHandoff({dir:tmp,out:manifest,role:'primary',executionId:'exec-link',pointer});assert(verifyHandoff({dir:tmp,manifestPath:manifest,requireCurrentSource:true}).ok);
  fs.writeFileSync(path.join(outside,'outside.txt'),'outside\n');let symlinkCreated=false;try{fs.unlinkSync(path.join(tmp,'payload.txt'));fs.symlinkSync(path.join(outside,'outside.txt'),path.join(tmp,'payload.txt'),'file');symlinkCreated=true}catch(e){if(!['EPERM','EACCES','ENOTSUP'].includes(e.code))throw e}
  if(symlinkCreated){const v=verifyHandoff({dir:tmp,manifestPath:manifest,requireCurrentSource:true});assert(!v.ok);assert(v.errors.some(x=>String(x).includes('HANDOFF_REPARSE_OR_SYMLINK_FORBIDDEN')));fs.unlinkSync(path.join(tmp,'payload.txt'));fs.writeFileSync(path.join(tmp,'payload.txt'),'inside\n')}
  assert.throws(()=>createHandoff({dir:tmp,out:manifest,role:'primary',executionId:'exec-link',pointer:path.join(outside,'outside.txt')}),/HANDOFF_POINTER_OUTSIDE_DIRECTORY/);
  console.log('rc1-handoff-reparse-failclosed PASS',{symlinkTamperExercised:symlinkCreated,pointerEscapeBlocked:true});
}finally{fs.rmSync(tmp,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});if(had)fs.writeFileSync(lock,old);else fs.rmSync(lock,{force:true})}
