const assert=require('assert');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const root=path.resolve(__dirname,'..');const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const {validate}=require('../scripts/stable-certification-policy.cjs');const {evaluateVerdict}=require('../scripts/rc1-stable-readiness.cjs');
const policy=validate(pkg);assert(policy.ok,policy.errors.join('|'));assert.equal(policy.policy.requireAuthenticode,true);assert.equal(policy.policy.requireArtifacts,true);assert.equal(policy.policy.requireDualWindows,true);assert.equal(policy.policy.requireManualEvidence,true);assert.equal(policy.policy.requireFinalBundle,true);assert.deepEqual(policy.policy.requiredScaleMatrix,[100000,1000000]);assert.equal(policy.policy.requireHashBoundAttachmentForManualPass,true);assert.equal(policy.policy.requiredManualEvidenceKeys.length,5);
function finalize(v){const copy={...v};delete copy.finalizationId;v.finalizationId=crypto.createHash('sha256').update(JSON.stringify(copy)).digest('hex');return v}
const base={schemaVersion:'workspace-agent-rc1-final-verdict-v4',version:pkg.version,toolingRevision:'cert-kit21',createdAt:new Date().toISOString(),executionId:'exec-policy-test',overall:'PASS',envelope:{evidenceId:'e'.repeat(64)},inputs:{},handoffs:{primary:{handoffId:'a'.repeat(64)},peer:{handoffId:'b'.repeat(64)}},windowsFamilies:{current:'Windows11',peer:'Windows10'},signingRequired:false,finalBundleRequired:true,stableCertificationPolicySha256:policy.sha256};
let r=evaluateVerdict(finalize({...base}),{stablePolicy:policy});assert(!r.ok);assert(r.reasons.includes('FINAL_SIGNING_POLICY_DOWNGRADE'));
r=evaluateVerdict(finalize({...base,signingRequired:true}),{stablePolicy:policy});assert(r.ok,r.reasons.join('|'));
r=evaluateVerdict(finalize({...base,signingRequired:true,finalBundleRequired:false}),{stablePolicy:policy});assert(!r.ok&&r.reasons.includes('FINAL_BUNDLE_POLICY_REQUIRED'));
r=evaluateVerdict(finalize({...base,signingRequired:true,stableCertificationPolicySha256:'0'.repeat(64)}),{stablePolicy:policy});assert(!r.ok&&r.reasons.includes('FINAL_STABLE_POLICY_HASH_MISMATCH'));
const execScript=fs.readFileSync(path.join(root,'scripts','windows-rc1-execution.ps1'),'utf8');assert(execScript.includes('STABLE_POLICY_SKIP_SCALE_FORBIDDEN'));assert(execScript.includes('$EffectiveRequireSigning=[bool]$RequireSigning -or [bool]$stablePolicy.requireAuthenticode'));
const certifyScript=fs.readFileSync(path.join(root,'scripts','windows-rc1-certify.ps1'),'utf8');assert(certifyScript.includes('STABLE_POLICY_NO_BUILD_ARTIFACTS_FORBIDDEN'));assert(certifyScript.includes('$EffectiveRequireSigning'));assert(certifyScript.includes("$envArgs+='--require-signing'"));
const legacyCertScript=fs.readFileSync(path.join(root,'scripts','windows-certification-v097.ps1'),'utf8');assert(legacyCertScript.includes('STABLE_POLICY_RUN_SCALE_REQUIRED'));assert(legacyCertScript.includes('STABLE_POLICY_BUILD_ARTIFACTS_REQUIRED'));assert(legacyCertScript.includes('test:windows-safe-handoff-transport-rc1-uat'));
console.log('stable-certification-policy-rc1 PASS',{nonDowngradableSigning:true,scaleSkipBlocked:true,artifactSkipBlocked:true,directRcScaleAndArtifactsRequired:true,finalBundleRequired:true,policyHashBound:true});
