const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const zlib=require('zlib');
const {StateBackupService}=require('../electron/services/state-backup-service.cjs');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wa-backup-'));
let applied=0,aiUpdated=0;
let currentConfig={schemaVersion:'workspace-agent-config-v1',automationRules:[{id:'r1',title:'r',root:dir,cycleType:'workspace-health',intervalMinutes:60,enabled:true}],managedZones:[],watchRoots:[]};
const configurationService={exportBundle:()=>JSON.parse(JSON.stringify(currentConfig)),validateExact:b=>JSON.parse(JSON.stringify(b)),replaceExact:b=>(applied++,currentConfig=JSON.parse(JSON.stringify(b)),{mode:'exact-replacement'})};
let currentAI={schemaVersion:'workspace-local-ai-config-v2',enabled:true,baseUrl:'http://127.0.0.1:8080/v1',model:'local'};
const localAIService={settings:()=>JSON.parse(JSON.stringify(currentAI)),replaceSettings:p=>(aiUpdated++,currentAI=JSON.parse(JSON.stringify(p)),currentAI)};
const index={listRoots:()=>[{root:dir,status:'completed',generation:2,completedAt:'x',files:10,bytes:20}]};
const svc=new StateBackupService(dir,{appVersion:'0.9.8',configurationService,localAIService,persistentFileIndex:index,journal:{append:()=>{}}});
const created=svc.create({reason:'test'});assert(fs.existsSync(created.file));const preview=svc.preview(created.file);assert.strictEqual(preview.summary.rules,1);assert.strictEqual(preview.summary.indexRoots,1);
currentConfig={schemaVersion:'workspace-agent-config-v1',automationRules:[],managedZones:[],watchRoots:[]};currentAI={...currentAI,enabled:false,model:'changed'};
const restored=svc.restore(created.file);assert.strictEqual(restored.ok,true);assert.strictEqual(applied,1);assert.strictEqual(aiUpdated,1);assert(restored.report.preRestoreBackup);assert.strictEqual(currentConfig.automationRules[0].id,'r1');assert.strictEqual(currentAI.model,'local');
const corrupted=path.join(dir,'bad.json.gz');const b=JSON.parse(zlib.gunzipSync(fs.readFileSync(created.file)).toString('utf8'));b.payload.configuration.automationRules.push({title:'tamper'});fs.writeFileSync(corrupted,zlib.gzipSync(Buffer.from(JSON.stringify(b))));assert.throws(()=>svc.preview(corrupted),e=>e.code==='BACKUP_INTEGRITY_FAILED');
console.log('state-backup-v098.test.cjs PASS');
