const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'src','App.jsx'),'utf8');
const timeline=fs.readFileSync(path.join(root,'src','components','CycleTimeline.jsx'),'utf8');
assert(app.includes("useRef,useState"),'App must use a ref-backed batch pump');
assert(app.includes('async function explorerBatchPump(seed)'),'automatic batch pump missing');
assert(app.includes("isAutoBatchCheckpoint(c)"),'normal checkpoint classifier missing');
assert(app.includes("control.mode='cancel'"),'safe cancel request must be serialized through the pump');
assert(app.includes("control.mode='pause'"),'safe pause request must stop future chunk resumes');
assert(app.includes("d==='approve'&&isAutoBatchCheckpoint(c)"),'approved batch must auto-continue after the first checkpoint');
assert(app.includes('autoRunning={batchAutoRunning&&batchPumpRef.current.cycleId===cycle?.id}'),'timeline must receive current auto-run state');
assert(timeline.includes('ادامه خودکار از Checkpoint'),'manual resume should restart automatic continuation');
assert(timeline.includes('مکث پس از Chunk جاری'),'running batch must expose safe-boundary pause');
assert(timeline.includes('لغو امن پس از Chunk جاری'),'running batch must expose safe-boundary cancel');
assert(app.includes('<span className="version">v1.0.0-rc1</span>'),'main UI version must match RC source');
assert(app.includes('<b>v1.0.0-rc1</b>'),'Explorer UI version must match RC source');
assert(!app.includes('<span className="version">v0.9.4</span>'),'stale app version label remains');
assert(!app.includes('<b>v0.9.6</b>'),'stale Explorer version label remains');
console.log('ui-batch-auto-progress-rc1.test.cjs PASS',{autoContinue:true,safePause:true,safeCancel:true,versionLabels:true});
