const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {VersionUpdateGuard,compareVersions,parseVersion}=require('../electron/services/version-update-guard.cjs');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wa-update-guard-'));
assert(compareVersions('1.0.0','0.9.9')>0);
assert(compareVersions('1.0.0-rc1','1.0.0')<0);
assert(compareVersions('1.0.0-rc2','1.0.0-rc1')>0);
assert.equal(parseVersion('1.0.0-rc1').valid,true);
assert.equal(parseVersion('1.0.0-rc1garbage+oops').valid,true);
assert.equal(parseVersion('1.0.0 trailing').valid,false);
assert.equal(parseVersion('1.0.0-01').valid,false);
assert.throws(()=>compareVersions('1.0.0oops','1.0.0'),e=>e.code==='VERSION_SEMVER_INVALID');
let g=new VersionUpdateGuard(dir,{currentVersion:'0.9.8'});
assert.throws(()=>g.prepareUpdate({targetVersion:'1.0.0junk',artifactSha256:'a'.repeat(64)}),e=>e.code==='UPDATE_TARGET_SEMVER_INVALID');
assert.strictEqual(g.assertWriteAllowed().ok,true);
g.prepareUpdate({targetVersion:'1.0.0-rc1',artifactSha256:'a'.repeat(64),backupFile:'state.json.gz'});
assert.strictEqual(g.status().pending.targetVersion,'1.0.0-rc1');
g=new VersionUpdateGuard(dir,{currentVersion:'1.0.0-rc1'});
assert.strictEqual(g.status().pending.firstBootAt!=null,true);
g.recordSelfCheck({at:new Date().toISOString(),overall:'block',summary:{block:1,warn:0}});
assert.strictEqual(g.assertWriteAllowed().ok,false);
assert.strictEqual(g.status().rollbackRecommended,true);
g.clearPending({reason:'test'});
assert.strictEqual(g.assertWriteAllowed().ok,true);
g.prepareUpdate({targetVersion:'1.0.0',artifactSha256:'b'.repeat(64)});
g=new VersionUpdateGuard(dir,{currentVersion:'1.0.0'});
g.recordSelfCheck({at:new Date().toISOString(),overall:'pass',summary:{block:0,warn:0}});
assert.strictEqual(g.status().stableVersion,'1.0.0');
assert.strictEqual(g.status().pending,null);
g=new VersionUpdateGuard(dir,{currentVersion:'0.9.9'});
assert.strictEqual(g.assertWriteAllowed().ok,false);
assert.strictEqual(g.status().blockCode,'APP_DOWNGRADE_DETECTED');

const epochDir=fs.mkdtempSync(path.join(os.tmpdir(),'wa-update-epoch-'));
fs.mkdirSync(path.join(epochDir,'runtime'),{recursive:true});
fs.writeFileSync(path.join(epochDir,'runtime','update-guard.json'),JSON.stringify({schemaVersion:'workspace-agent-update-guard-v1',dataEpoch:2,stableVersion:'1.1.0',lastSeenVersion:'1.1.0',pending:null,lastSelfCheck:null,rollbackRecommended:false,writeBlocked:false,blockCode:null,history:[]}));
const epochGuard=new VersionUpdateGuard(epochDir,{currentVersion:'1.0.0'});assert.strictEqual(epochGuard.status().blockCode,'STATE_DATA_EPOCH_TOO_NEW');assert.strictEqual(epochGuard.assertWriteAllowed().ok,false);
console.log('version-update-guard-v098.test.cjs PASS');
