const fs=require('fs');const os=require('os');const path=require('path');const cp=require('child_process');
const strict=process.env.WA_CERT_STRICT==='1';
function finish(status,detail={},code=status==='PASS'?0:status==='INCOMPLETE'?3:1){const out={schemaVersion:'workspace-agent-windows-safe-handoff-transport-uat-v1',createdAt:new Date().toISOString(),platform:process.platform,status,...detail};const file=process.env.WA_CERT_SAFE_HANDOFF_RESULT;if(file){fs.mkdirSync(path.dirname(path.resolve(file)),{recursive:true});fs.writeFileSync(path.resolve(file),JSON.stringify(out,null,2));}console.log(JSON.stringify(out,null,2));process.exit(code)}
if(process.platform!=='win32')finish(strict?'INCOMPLETE':'SKIP',{code:'WINDOWS_REQUIRED'},strict?3:0);
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-safe-handoff-'));
const ps='powershell.exe';
function run(args){return cp.spawnSync(ps,args,{cwd:root,encoding:'utf8'});}
function safeExpand(zip,dest,extra=[]){return run(['-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/windows-safe-archive-expand.ps1','-Archive',zip,'-Destination',dest,...extra]);}
function quotePs(s){return `'${String(s).replace(/'/g,"''")}'`}
function makeZip(entries,zip){const body=entries.map(([name,data])=>`$e=$z.CreateEntry(${quotePs(name)});$w=New-Object IO.StreamWriter($e.Open());$w.Write(${quotePs(data)});$w.Dispose();`).join('');const cmd=`Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction SilentlyContinue;$z=[IO.Compression.ZipFile]::Open(${quotePs(zip)},[IO.Compression.ZipArchiveMode]::Create);try{${body}}finally{$z.Dispose()}`;const r=run(['-NoProfile','-Command',cmd]);if(r.status!==0)throw new Error(`ZIP_FIXTURE_FAILED:${r.stderr||r.stdout}`)}
try{
  const safeSrc=path.join(tmp,'safe-src'),safeZip=path.join(tmp,'safe.zip'),safeDest=path.join(tmp,'safe-out');fs.mkdirSync(safeSrc);fs.writeFileSync(path.join(safeSrc,'evidence.txt'),'safe-evidence');let r=run(['-NoProfile','-Command',`Compress-Archive -LiteralPath ${quotePs(path.join(safeSrc,'evidence.txt'))} -DestinationPath ${quotePs(safeZip)} -Force`]);if(r.status!==0)throw new Error(r.stderr||r.stdout);r=safeExpand(safeZip,safeDest);if(r.status!==0||!fs.existsSync(path.join(safeDest,'evidence.txt')))throw new Error(`SAFE_ARCHIVE_REJECTED:${r.stderr||r.stdout}`);
  const sentinelDest=path.join(tmp,'sentinel-dest');fs.mkdirSync(sentinelDest);fs.writeFileSync(path.join(sentinelDest,'keep.txt'),'keep');const traversal=path.join(tmp,'traversal.zip');makeZip([['../escape.txt','escape']],traversal);r=safeExpand(traversal,sentinelDest);if(r.status===0)throw new Error('TRAVERSAL_ARCHIVE_WAS_ACCEPTED');if(fs.existsSync(path.join(tmp,'escape.txt')))throw new Error('ZIP_SLIP_CREATED_OUTSIDE_FILE');if(fs.readFileSync(path.join(sentinelDest,'keep.txt'),'utf8')!=='keep')throw new Error('INVALID_ARCHIVE_DESTROYED_EXISTING_DESTINATION');
  const ads=path.join(tmp,'ads.zip');makeZip([['evidence.txt:evil','ads']],ads);r=safeExpand(ads,path.join(tmp,'ads-out'));if(r.status===0)throw new Error('ADS_ARCHIVE_WAS_ACCEPTED');
  const dup=path.join(tmp,'dup.zip');makeZip([['A.txt','a'],['a.txt','b']],dup);r=safeExpand(dup,path.join(tmp,'dup-out'));if(r.status===0)throw new Error('CASE_ALIAS_DUPLICATE_WAS_ACCEPTED');
  const bounded=path.join(tmp,'bounded.zip');makeZip([['large.txt','0123456789']],bounded);r=safeExpand(bounded,path.join(tmp,'bounded-out'),['-MaxTotalUncompressedBytes','4']);if(r.status===0)throw new Error('ARCHIVE_SIZE_BOUND_WAS_NOT_ENFORCED');
  finish('PASS',{code:'SAFE_HANDOFF_ARCHIVE_BOUNDARY_VERIFIED',checks:{safeExtract:true,traversalBlocked:true,destinationPreservedOnReject:true,adsBlocked:true,caseAliasBlocked:true,sizeBound:true}});
}catch(e){finish('FAIL',{code:'SAFE_HANDOFF_TRANSPORT_UAT_FAILED',message:String(e.message||e).slice(0,1200)},1)}finally{try{fs.rmSync(tmp,{recursive:true,force:true})}catch{}}
