const fs=require('fs');const os=require('os');const path=require('path');const assert=require('assert');const {spawn}=require('child_process');
const {UIGroundingService}=require('../electron/services/ui-grounding-service.cjs');
const {deriveAdaptiveCropPlan}=require('../electron/services/vision-crop-service.cjs');
if(process.platform!=='win32'){console.log('windows-production-grounding-v093.uat.cjs SKIP (Windows only)');process.exit(0)}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-v093-')),ready=path.join(tmp,'ready.txt');const ps=path.join(tmp,'fixture.ps1');
fs.writeFileSync(ps,`$ErrorActionPreference='Stop'\nAdd-Type -AssemblyName System.Windows.Forms\n$form=New-Object System.Windows.Forms.Form;$form.Text='Grounding Main';$form.Name='GroundingMain';$form.Width=900;$form.Height=650;$form.StartPosition='CenterScreen'\n$main=New-Object System.Windows.Forms.Button;$main.Text='Save';$main.Name='saveMain';$main.Left=700;$main.Top=520;$main.Width=100\n$form.Controls.Add($main)\n$form.Add_Shown({Set-Content -LiteralPath '${ready.replace(/'/g,"''")}' -Value ([string]$PID);$d=New-Object System.Windows.Forms.Form;$d.Text='Save As';$d.Name='SaveDialog';$d.Width=520;$d.Height=330;$d.StartPosition='CenterParent';$b=New-Object System.Windows.Forms.Button;$b.Text='Save';$b.Name='saveDialog';$b.Left=350;$b.Top=220;$b.Width=100;$d.Controls.Add($b);[void]$d.ShowDialog($form)})\n[void]$form.ShowDialog()`,'utf8');
const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',ps],{stdio:'ignore',windowsHide:true});
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}async function wait(){for(let i=0;i<100;i++){if(fs.existsSync(ready))return Number(fs.readFileSync(ready,'utf8').trim());await sleep(100)}throw new Error('fixture timeout')}
(async()=>{let pid;try{pid=await wait();await sleep(700);const svc=new UIGroundingService(tmp);const g=await svc.ground('Save in the dialog',{maxNodes:1000,limit:10});assert(g.ok);const top=g.result.candidates[0];assert(/save/i.test(top.element.name));assert(top.element.surfaceIsModal||top.element.surfaceKind==='dialog');assert((g.displays||[]).length>=1);const row=svc.getSession(g.sessionToken);const display=(row.map.displays||[])[0];const w=row.map.focusedWindow?.rect;if(w&&display?.bounds){const plan=deriveAdaptiveCropPlan({windowRect:w,candidateRects:[top.element.rect],displays:row.map.displays,imageWidth:Math.round(w.width),imageHeight:Math.round(w.height)});assert(plan.ok&&plan.mapping.source==='window');}console.log('windows-production-grounding-v093.uat.cjs PASS',{pid,surfaces:g.surfaces?.length||0,displays:g.displays?.length||0,topSurface:top.element.surfaceKind});}finally{try{if(pid)process.kill(pid)}catch{}try{child.kill()}catch{}fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);try{child.kill()}catch{}process.exit(1)});
