const fs=require('fs');const os=require('os');const path=require('path');const assert=require('assert');const {spawn}=require('child_process');
const {UIGroundingService}=require('../electron/services/ui-grounding-service.cjs');
const {prepareWindowsUiAction,executePinnedWindowsUiAction}=require('../electron/services/windows-uia-actions.cjs');
const {deriveCropPlan}=require('../electron/services/vision-crop-service.cjs');
const {LocalAIService}=require('../electron/services/local-ai-service.cjs');
if(process.platform!=='win32'){console.log('windows-intelligent-grounding-v092.uat.cjs SKIP (Windows only)');process.exit(0)}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wa-v092-'));const ready=path.join(tmp,'ready.txt');const shot=path.join(tmp,'window.png');const crop=path.join(tmp,'crop.png');
const ps=path.join(tmp,'fixture.ps1');fs.writeFileSync(ps,`$ErrorActionPreference='Stop'\nAdd-Type -AssemblyName System.Windows.Forms\nAdd-Type -AssemblyName System.Drawing\n$form=New-Object System.Windows.Forms.Form\n$form.Text='Workspace Agent Grounding Fixture'\n$form.Name='GroundingFixture'\n$form.Width=760;$form.Height=460;$form.StartPosition='CenterScreen';$form.TopMost=$true\n$label=New-Object System.Windows.Forms.Label;$label.Text='Not saved';$label.Name='statusLabel';$label.Left=40;$label.Top=40;$label.Width=300\n$button=New-Object System.Windows.Forms.Button;$button.Text='Save settings';$button.Name='saveSettings';$button.Left=520;$button.Top=330;$button.Width=150;$button.Height=40\n$button.Add_Click({$label.Text='Saved successfully'})\n$form.Controls.Add($label);$form.Controls.Add($button)\n$form.Add_Shown({Set-Content -LiteralPath '${ready.replace(/'/g,"''")}' -Value ([string]$PID);$form.Activate()})\n[void]$form.ShowDialog()\n`,'utf8');
const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',ps],{stdio:'ignore',windowsHide:true});
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}async function waitReady(){for(let i=0;i<80;i++){if(fs.existsSync(ready))return Number(fs.readFileSync(ready,'utf8').trim());await sleep(100)}throw new Error('fixture startup timeout')}
async function screenshotWindow(pid,file){const script=`$ErrorActionPreference='Stop';Add-Type -AssemblyName UIAutomationClient;Add-Type -AssemblyName UIAutomationTypes;Add-Type -AssemblyName System.Drawing;$root=[System.Windows.Automation.AutomationElement]::RootElement;$wins=$root.FindAll([System.Windows.Automation.TreeScope]::Children,[System.Windows.Automation.Condition]::TrueCondition);$w=$null;for($i=0;$i -lt $wins.Count;$i++){if($wins.Item($i).Current.ProcessId -eq ${pid}){$w=$wins.Item($i);break}};if($null -eq $w){throw 'window not found'};$r=$w.Current.BoundingRectangle;$bmp=New-Object System.Drawing.Bitmap ([int]$r.Width),([int]$r.Height);$g=[System.Drawing.Graphics]::FromImage($bmp);$g.CopyFromScreen([int]$r.Left,[int]$r.Top,0,0,$bmp.Size);$bmp.Save('${file.replace(/'/g,"''")}',[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose();[ordered]@{left=$r.Left;top=$r.Top;width=$r.Width;height=$r.Height}|ConvertTo-Json -Compress`;
 return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command',script],{windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('exit',c=>c===0?resolve(JSON.parse(out.trim())):reject(new Error(err||`screenshot exit ${c}`)));});}
async function cropWithPowerShell(src,dst,rect){const script=`Add-Type -AssemblyName System.Drawing;$img=[System.Drawing.Image]::FromFile('${src.replace(/'/g,"''")}');$r=New-Object System.Drawing.Rectangle ${rect.x},${rect.y},${rect.width},${rect.height};$bmp=New-Object System.Drawing.Bitmap $r.Width,$r.Height;$g=[System.Drawing.Graphics]::FromImage($bmp);$g.DrawImage($img,0,0,$r,[System.Drawing.GraphicsUnit]::Pixel);$bmp.Save('${dst.replace(/'/g,"''")}',[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose();$img.Dispose()`;return new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-Command',script],{windowsHide:true});let err='';p.stderr.on('data',d=>err+=d);p.on('exit',c=>c===0?resolve():reject(new Error(err||`crop exit ${c}`)));});}
(async()=>{let pid;try{pid=await waitReady();await sleep(400);const svc=new UIGroundingService(tmp);const grounded=await svc.ground('Save settings button',{limit:6});assert(grounded.ok);const top=grounded.result.candidates[0];assert(/save/i.test(top.element.name));const ctx=svc.actionContext(grounded.sessionToken,top.id);const prepared=await prepareWindowsUiAction({action:'invoke',selector:ctx.selector});assert(prepared.ok);const executed=await executePinnedWindowsUiAction(prepared.plan,'');assert(executed.ok&&executed.verification?.ok);svc.recordVerifiedAction({grounding:ctx.grounding},'invoke');await sleep(200);const map=svc.getSession(grounded.sessionToken).map;const wr=await screenshotWindow(pid,shot);const stat=fs.statSync(shot);assert(stat.size>0);const plan=deriveCropPlan({windowRect:map.focusedWindow.rect,candidateRects:[top.element.rect],imageWidth:Math.round(wr.width),imageHeight:Math.round(wr.height)});assert(plan.ok);await cropWithPowerShell(shot,crop,plan.rect);assert(fs.statSync(crop).size>0);
 let vision='SKIP';if(process.env.WA_LOCAL_AI_BASE_URL&&process.env.WA_LOCAL_AI_MODEL){const ai=new LocalAIService(tmp);ai.updateSettings({enabled:true,allowVision:true,baseUrl:process.env.WA_LOCAL_AI_BASE_URL,model:process.env.WA_LOCAL_AI_MODEL});const data=`data:image/png;base64,${fs.readFileSync(crop).toString('base64')}`;const v=await ai.analyzeUiGroundingData({imageDataUrl:data,intent:'Save settings button',candidates:[top],crop:{applied:true,cropFraction:plan.cropFraction,mapping:plan.mapping.source}});vision=v.matches.length?'PASS':'CHECK';}
 console.log('windows-intelligent-grounding-v092.uat.cjs PASS',{pid,top:top.element.name,confidence:grounded.result.topConfidence,cropFraction:plan.cropFraction,vision});}finally{try{if(pid)process.kill(pid)}catch{}try{child.kill()}catch{}fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);try{child.kill()}catch{}process.exit(1)});
