const { dialog, shell, nativeImage } = require('electron');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { deriveCropPlan } = require('./services/vision-crop-service.cjs');
const { deterministicOutcome, fuseVisual } = require('./services/ui-outcome-verifier.cjs');
const { capabilitySummary } = require('./services/capability-registry.cjs');
const { registrySummary } = require('./services/skill-registry.cjs');
const { planGoal } = require('./services/goal-planner.cjs');
const {trustedSender}=require('./services/runtime-trust-policy.cjs');
const {ClaudeFileAgent,applyPlan}=require('./services/claude-file-agent.cjs');
function deny(){ return {ok:false,code:'UNTRUSTED_IPC'}; }

function imageDataUrlForVision(file,{windowRect=null,candidateRects=[],displays=[],maxDimension=2048}={}){
  const stat=fs.statSync(file);if(!stat.isFile()||stat.size>40*1024*1024)throw Object.assign(new Error('Screenshot انتخابی بیش از سقف ورودی است.'),{code:'VISION_SOURCE_FILE_LIMIT'});
  let image=nativeImage.createFromPath(file);if(image.isEmpty())throw Object.assign(new Error('تصویر انتخابی قابل خواندن نیست.'),{code:'VISION_IMAGE_DECODE_FAILED'});
  const source=image.getSize();const plan=deriveCropPlan({windowRect,candidateRects,displays,imageWidth:source.width,imageHeight:source.height});let applied=false;
  if(plan.ok){image=image.crop(plan.rect);applied=true;}
  let size=image.getSize();if(Math.max(size.width,size.height)>maxDimension){const scale=maxDimension/Math.max(size.width,size.height);image=image.resize({width:Math.max(1,Math.round(size.width*scale)),height:Math.max(1,Math.round(size.height*scale)),quality:'best'});size=image.getSize();}
  let mime='image/png',buf=image.toPNG();if(buf.length>8*1024*1024){mime='image/jpeg';buf=image.toJPEG(92);}return{imageDataUrl:`data:${mime};base64,${buf.toString('base64')}`,meta:{applied,cropFraction:plan.ok?plan.cropFraction:1,mapping:plan.ok?plan.mapping.source:'unmapped-user-image',mappingConfidence:plan.ok?plan.mapping.confidence:'untrusted',mappingCode:plan.ok?'OK':plan.code,sourceSize:source,outputSize:size}};
}
function registerIpc({ ipcMain, engine, store, snapshotStore, automationStore, automationService, reviewQueueStore, managedZoneStore, storageTrendStore, journal, recoveryService, watcherService, configurationService, windowsActionSessionStore, persistentFileIndex, rootResilienceService, lifecycleState=null, resourcePressureGuard=null, localAIService=null, uiGroundingService=null, explorerBatchStore=null, updateGuard=null, rcSelfCheckService=null, stateBackupService=null, diagnosticsBundleService=null, explorerOperationCoordinator=null, rendererTrustPolicy=null }) {
  const trusted=e=>trustedSender(e,rendererTrustPolicy||{});
  const importTokens=new Map();
  const backupRestoreTokens=new Map();
  const explorerDestinationTokens=new Map();
  const pruneExpiringTokens=map=>{const t=Date.now();for(const [k,v] of map)if(Number(v?.expiresAt||0)<=t)map.delete(k);};
  const pruneExplorerDestinationTokens=()=>pruneExpiringTokens(explorerDestinationTokens);
  ipcMain.handle('wa:select-folder', async e => trusted(e) ? (await dialog.showOpenDialog({properties:['openDirectory']})).filePaths[0] || '' : '');
  ipcMain.handle('wa:explorer-pick-destination-root', async e => {if(!trusted(e))return deny();const r=await dialog.showOpenDialog({title:'انتخاب Root مقصد File Explorer Batch',properties:['openDirectory']});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true};pruneExplorerDestinationTokens();const token=`explorer-dst-${Date.now()}-${crypto.randomBytes(12).toString('hex')}`;const root=path.resolve(r.filePaths[0]);explorerDestinationTokens.set(token,{root,expiresAt:Date.now()+10*60*1000});return{ok:true,token,displayPath:root,expiresAt:new Date(Date.now()+10*60*1000).toISOString()};});
  ipcMain.handle('wa:cycles', e => trusted(e) ? store.list(100) : deny());
  ipcMain.handle('wa:capabilities', e => trusted(e) ? capabilitySummary() : deny());
  ipcMain.handle('wa:skills', e => trusted(e) ? registrySummary() : deny());
  ipcMain.handle('wa:index-status', async (e,root='') => trusted(e) ? (persistentFileIndex?persistentFileIndex.status(root):{schemaVersion:'persistent-index-v2',root:path.resolve(String(root||'.')),status:'unavailable',files:0,bytes:0,queue:0,generation:0,errors:0,code:'INDEX_SQLITE_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:index-roots', e => trusted(e) ? (persistentFileIndex?persistentFileIndex.listRoots():[]) : deny());
  ipcMain.handle('wa:index-health', (e,deep=false) => trusted(e) ? (persistentFileIndex?persistentFileIndex.health({deep:Boolean(deep)}):{ok:false,code:'INDEX_SQLITE_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:index-search', (e,input={}) => trusted(e) ? (persistentFileIndex?persistentFileIndex.search(input||{}):{ok:false,code:'INDEX_SQLITE_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:index-errors', (e,root='',limit=200) => trusted(e) ? (persistentFileIndex?persistentFileIndex.recentErrors(root,{limit}):[]) : deny());
  ipcMain.handle('wa:snapshots', (e,root='') => trusted(e) ? snapshotStore.list(root) : deny());
  ipcMain.handle('wa:plan-goal', (e,command='') => trusted(e) ? planGoal(command) : deny());
  ipcMain.handle('wa:ai-status', e => trusted(e) ? (localAIService?localAIService.status():{ok:false,code:'AI_RUNTIME_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:ai-settings', e => trusted(e) ? (localAIService?localAIService.settings():{ok:false,code:'AI_RUNTIME_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:ai-settings-update', (e,patch={}) => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,settings:localAIService.updateSettings(patch)}}catch(error){return{ok:false,code:error.code||'AI_SETTINGS_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-health', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};return localAIService.health();});
  ipcMain.handle('wa:ai-hardware-profile', async (e,visionPreferred=false) => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,profile:await localAIService.hardwareProfile({visionPreferred:Boolean(visionPreferred)})}}catch(error){return{ok:false,code:error.code||'AI_HARDWARE_PROFILE_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-apply-hardware-advice', (e,advice={}) => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,settings:localAIService.applyHardwareAdvice(advice)}}catch(error){return{ok:false,code:error.code||'AI_HARDWARE_ADVICE_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-runtime-status', e => trusted(e) ? (localAIService?localAIService.runtimeStatus():{ok:false,code:'AI_RUNTIME_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:ai-runtime-trust', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,trust:await localAIService.runtimeTrust()}}catch(error){return{ok:false,code:error.code||'AI_RUNTIME_TRUST_FAILED',message:error.message,trust:error.trust||null}}});
  ipcMain.handle('wa:ai-runtime-selection', e => trusted(e) ? (localAIService?localAIService.runtimeSelection():{ok:false,code:'AI_RUNTIME_UNAVAILABLE'}) : deny());
  ipcMain.handle('wa:ai-runtime-pick-executable', async e => {if(!trusted(e))return deny();const filters=process.platform==='win32'?[{name:'llama-server',extensions:['exe']}]:[{name:'llama-server',extensions:['*']}];const r=await dialog.showOpenDialog({title:'انتخاب llama-server',properties:['openFile'],filters});return r.canceled||!r.filePaths[0]?{ok:false,cancelled:true}:{ok:true,filePath:r.filePaths[0]};});
  ipcMain.handle('wa:ai-runtime-pick-model', async e => {if(!trusted(e))return deny();const r=await dialog.showOpenDialog({title:'انتخاب مدل GGUF',properties:['openFile'],filters:[{name:'GGUF model',extensions:['gguf']}]});return r.canceled||!r.filePaths[0]?{ok:false,cancelled:true}:{ok:true,filePath:r.filePaths[0]};});
  ipcMain.handle('wa:ai-runtime-start', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,runtime:await localAIService.startManagedRuntime()}}catch(error){return{ok:false,code:error.code||'AI_RUNTIME_START_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-runtime-stop', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,runtime:await localAIService.stopManagedRuntime()}}catch(error){return{ok:false,code:error.code||'AI_RUNTIME_STOP_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-runtime-restart', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return{ok:true,runtime:await localAIService.restartManagedRuntime()}}catch(error){return{ok:false,code:error.code||'AI_RUNTIME_RESTART_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-capability-probe', async (e,includeVision=false) => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return await localAIService.capabilityProbe({includeVision:Boolean(includeVision)})}catch(error){return{ok:false,code:error.code||'AI_CAPABILITY_PROBE_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-warmup', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return await localAIService.warmup()}catch(error){return{ok:false,code:error.code||'AI_WARMUP_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-ground-ui', async (e,intent='') => {if(!trusted(e))return deny();if(!uiGroundingService)return{ok:false,code:'UI_GROUNDING_UNAVAILABLE'};try{return await uiGroundingService.ground(intent,{maxNodes:700,maxWindows:80,limit:8})}catch(error){return{ok:false,code:error.code||'UI_GROUNDING_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-ground-ui-vision', async (e,sessionToken='') => {if(!trusted(e))return deny();if(!uiGroundingService||!localAIService)return{ok:false,code:'UI_GROUNDING_UNAVAILABLE'};try{const row=uiGroundingService.getSession(sessionToken);const r=await dialog.showOpenDialog({title:'Screenshot پنجره فعال را برای Vision corroboration انتخاب کنید',properties:['openFile'],filters:[{name:'Image',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true};const top=(row.result?.candidates||[]).slice(0,4);const img=imageDataUrlForVision(r.filePaths[0],{windowRect:row.map?.focusedWindow?.rect,candidateRects:top.map(x=>x.element?.rect).filter(Boolean),displays:row.map?.displays||[]});const vision=await localAIService.analyzeUiGroundingData({imageDataUrl:img.imageDataUrl,intent:row.intent||'',candidates:top,crop:img.meta});const fused=uiGroundingService.applyVision(sessionToken,vision);return{...fused,vision:{summary:vision.summary,warnings:vision.warnings,model:vision.model,latencyMs:vision.latencyMs,crop:img.meta}};}catch(error){return{ok:false,code:error.code||'UI_GROUNDING_VISION_FAILED',message:error.message}}});
  ipcMain.handle('wa:start-uia-grounded-action', async (e,input={}) => {if(!trusted(e))return deny();if(!uiGroundingService)return{ok:false,code:'UI_GROUNDING_UNAVAILABLE'};try{const ctx=await uiGroundingService.refreshActionContext(input.sessionToken,input.candidateId);if(Number(ctx.grounding.confidence||0)<0.35)return{ok:false,code:'UI_GROUNDING_CONFIDENCE_TOO_LOW',message:'Candidate برای Action حتی پس از انتخاب کاربر بیش از حد ضعیف است؛ UI Map را دوباره بسازید.'};const session=windowsActionSessionStore.create({action:input.action,selector:ctx.selector,value:input.value||'',sensitive:false},{context:{grounding:ctx.grounding}});if(!session.ok)return session;const r=session.redacted;const c=engine.create('windows-ui-action',{sessionToken:session.token,action:r.action,selector:r.selector,valueHash:r.valueHash||null,valueLength:r.valueLength||0},{source:'interactive-grounded-uia',budget:{maxIterations:4,maxWallTimeMs:10*60*1000}});return engine.run(c.id);}catch(error){return{ok:false,code:error.code||'UI_GROUNDED_ACTION_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-verify-uia-cycle', async (e,cycleId='') => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{const cycle=store.get(cycleId);const base=deterministicOutcome(cycle||{});if(!base.ok)return base;const r=await dialog.showOpenDialog({title:'Screenshot پس از Action را برای Visual verification انتخاب کنید',properties:['openFile'],filters:[{name:'Image',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled||!r.filePaths[0])return{...base,cancelled:true};let windowRect=null,targetRect=cycle?.result?.execution?.after?.rect||cycle?.result?.execution?.before?.rect||null;try{const now=await uiGroundingService?.inspect?.({maxNodes:250});if(now?.supported&&Number(now?.window?.processId||0)===Number(cycle?.actionPlan?.target?.processId||0))windowRect=now.window?.rect||null;}catch{}let displays=[];try{const now2=await uiGroundingService?.inspect?.({maxNodes:40});displays=now2?.displays||[]}catch{}const img=imageDataUrlForVision(r.filePaths[0],{windowRect,candidateRects:targetRect?[targetRect]:[],displays});const visual=await localAIService.verifyUiOutcomeData({imageDataUrl:img.imageDataUrl,action:base.action,target:base.target});return{...fuseVisual(base,visual),visionMeta:{model:visual.model,latencyMs:visual.latencyMs,crop:img.meta}};}catch(error){return{ok:false,code:error.code||'UI_VISUAL_VERIFY_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-ui-assist', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{const c=engine.create('windows-ui-map',{maxNodes:500,maxWindows:80},{source:'ai-ui-assist',budget:{maxIterations:4,maxWallTimeMs:30000}});const done=await engine.run(c.id);const map=done?.result||null;const count=Number(map?.elements?.length||0);if(map?.supported&&count>=8)return{ok:true,schemaVersion:'workspace-ai-ui-assist-v1',source:'uia',reason:'UIA_SUFFICIENT',uia:map,vision:null,policy:{uiaFirst:true,automaticScreenshot:false}};const r=await dialog.showOpenDialog({title:'UIA کافی نبود؛ تصویر Screenshot را برای Vision انتخاب کنید',properties:['openFile'],filters:[{name:'Image',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true,source:'uia-insufficient',uia:map,policy:{uiaFirst:true,automaticScreenshot:false}};const vision=await localAIService.analyzeImageFile(r.filePaths[0]);return{ok:true,schemaVersion:'workspace-ai-ui-assist-v1',source:'vision-fallback',reason:map?.supported?'UIA_LOW_SIGNAL':'UIA_UNSUPPORTED',uia:map,vision,policy:{uiaFirst:true,automaticScreenshot:false}};}catch(error){return{ok:false,code:error.code||'AI_UI_ASSIST_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-plan', async (e,command='',root='') => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{return await localAIService.plan(command,{root});}catch(error){return{ok:false,code:error.code||'AI_PLAN_FAILED',message:error.message,retryAfterMs:error.retryAfterMs||null}}});
  ipcMain.handle('wa:ai-start-mission', async (e,planToken='',root='') => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};try{const rec=localAIService.consumePlan(planToken,{root});const c=engine.create('mission',{root,command:'[LOCAL_AI_PLAN]',goalPlan:rec.goalPlan,planSource:'local-ai-token',aiCommandHash:rec.commandHash},{source:'local-ai-token',budget:{maxIterations:80,maxWallTimeMs:30*60*1000}});return await engine.run(c.id);}catch(error){return{ok:false,code:error.code||'AI_MISSION_START_FAILED',message:error.message}}});
  ipcMain.handle('wa:ai-vision-file', async e => {if(!trusted(e))return deny();if(!localAIService)return{ok:false,code:'AI_RUNTIME_UNAVAILABLE'};const r=await dialog.showOpenDialog({title:'انتخاب تصویر برای Local Vision',properties:['openFile'],filters:[{name:'Image',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true};try{return await localAIService.analyzeImageFile(r.filePaths[0]);}catch(error){return{ok:false,code:error.code||'AI_VISION_FAILED',message:error.message}}});
  ipcMain.handle('wa:start-cycle', async (e,type,input={}) => { if(!trusted(e)) return deny(); const explorerWrites=new Set(['explorer-new-folder','explorer-copy','explorer-move','explorer-rename','explorer-batch-copy','explorer-batch-move']); if(String(type)==='windows-ui-action')return{ok:false,code:'RESTRICTED_CYCLE_ENTRYPOINT',message:'Windows UI Action فقط از entrypoint تعاملی امن با ephemeral session قابل شروع است.'}; if(explorerWrites.has(String(type)))return{ok:false,code:'RESTRICTED_EXPLORER_WRITE_ENTRYPOINT',message:'File Explorer Write فقط از entrypoint تعاملی اختصاصی قابل شروع است.'}; if(String(type)==='mission'&&(input?.goalPlan||input?.planToken||input?.planSource))return{ok:false,code:'AI_PLAN_DIRECT_INJECTION_BLOCKED',message:'AI Plan فقط با token موقت صادرشده از Local AI Service قابل اجراست.'}; const c=engine.create(type,input); const result=await engine.run(c.id);if(String(type)==='persistent-index-scan'&&result?.status==='completed'&&input?.root){watcherService.clearDirty(input.root);if(input?.resume===false)await rootResilienceService?.acknowledgeRoot?.(input.root);}return result; });
  ipcMain.handle('wa:start-explorer-write', async (e,type,input={}) => {
    if(!trusted(e))return deny();const allowed=new Set(['explorer-new-folder','explorer-copy','explorer-move','explorer-rename']);if(!allowed.has(String(type)))return{ok:false,code:'EXPLORER_WRITE_TYPE_BLOCKED'};
    try{const c=engine.create(String(type),input,{source:'interactive-file-explorer',budget:{maxIterations:6,maxWallTimeMs:30*60*1000}});return await engine.run(c.id);}catch(error){return{ok:false,code:error.code||'EXPLORER_WRITE_START_FAILED',message:error.message,details:error.details||null};}
  });
  ipcMain.handle('wa:start-explorer-batch', async (e,type,input={}) => {
    if(!trusted(e))return deny();if(!explorerBatchStore)return{ok:false,code:'EXPLORER_BATCH_UNAVAILABLE'};const allowed=new Set(['explorer-batch-copy','explorer-batch-move']);if(!allowed.has(String(type)))return{ok:false,code:'EXPLORER_BATCH_TYPE_BLOCKED'};
    try{pruneExplorerDestinationTokens();const safeInput={...input};delete safeInput.destinationRoot;const token=String(input?.destinationRootToken||'');delete safeInput.destinationRootToken;if(token){const row=explorerDestinationTokens.get(token);if(!row||row.expiresAt<=Date.now()){explorerDestinationTokens.delete(token);return{ok:false,code:'EXPLORER_DESTINATION_TOKEN_EXPIRED',message:'انتخاب Root مقصد منقضی شده است؛ دوباره پوشه مقصد را انتخاب کنید.'};}safeInput.destinationRoot=row.root;explorerDestinationTokens.delete(token);}else safeInput.destinationRoot=path.resolve(String(input?.root||''));const c=engine.create(String(type),safeInput,{source:'interactive-file-explorer-batch',budget:{maxIterations:10000,maxWallTimeMs:12*60*60*1000}});return await engine.run(c.id);}catch(error){return{ok:false,code:error.code||'EXPLORER_BATCH_START_FAILED',message:error.message,details:error.details||null};}
  });
  ipcMain.handle('wa:explorer-batch-resume', async (e,cycleId='') => {if(!trusted(e))return deny();try{return await engine.resume(String(cycleId))}catch(error){return{ok:false,code:error.code||'EXPLORER_BATCH_RESUME_FAILED',message:error.message}}});
  ipcMain.handle('wa:explorer-batch-cancel', async (e,cycleId='') => {if(!trusted(e))return deny();try{return await engine.cancel(String(cycleId))}catch(error){return{ok:false,code:error.code||'EXPLORER_BATCH_CANCEL_FAILED',message:error.message}}});
  ipcMain.handle('wa:explorer-batch-status', (e,jobId='') => trusted(e) ? (explorerBatchStore?.status?.(String(jobId))||{ok:false,code:'EXPLORER_BATCH_JOB_NOT_FOUND'}) : deny());
  ipcMain.handle('wa:start-uia-action', async (e,request={}) => {
    if(!trusted(e))return deny();
    const session=windowsActionSessionStore.create(request);if(!session.ok)return session;
    try{const r=session.redacted;const c=engine.create('windows-ui-action',{sessionToken:session.token,action:r.action,selector:r.selector,valueHash:r.valueHash||null,valueLength:r.valueLength||0},{source:'interactive-uia',budget:{maxIterations:4,maxWallTimeMs:10*60*1000}});return engine.run(c.id);}catch(error){windowsActionSessionStore.forget(session.token);return{ok:false,code:error.code||'UIA_ACTION_START_FAILED',message:error.message};}
  });
  const claudeAgent=new ClaudeFileAgent();const agentPlans=new Map();
  ipcMain.handle('wa:agent-status', e => trusted(e) ? {ok:true,keyPresent:Boolean(process.env.ANTHROPIC_API_KEY),model:claudeAgent.model} : deny());
  ipcMain.handle('wa:agent-run', async (e,command='',root='') => {
    if(!trusted(e))return deny();
    try{
      const out=await claudeAgent.run({command:String(command),root:String(root)});
      for(const [k,v] of agentPlans)if(v.expiresAt<=Date.now())agentPlans.delete(k);
      if(out.plan)agentPlans.set(out.id,{plan:out.plan,root:path.resolve(String(root)),expiresAt:Date.now()+30*60*1000});
      return {ok:true,planId:out.plan?out.id:null,plan:out.plan,message:out.message,usage:out.usage,model:out.model};
    }catch(error){return {ok:false,code:error.code||'AGENT_FAILED',message:error.message};}
  });
  ipcMain.handle('wa:agent-apply', async (e,planId='') => {
    if(!trusted(e))return deny();
    const rec=agentPlans.get(String(planId));if(!rec||rec.expiresAt<=Date.now())return {ok:false,code:'AGENT_PLAN_EXPIRED',message:'Plan منقضی شده است؛ دوباره اجرا کنید.'};
    agentPlans.delete(String(planId));
    let results=[];
    try{
      const out=await applyPlan({engine,root:rec.root,plan:rec.plan});results=out.results;return out;
    }catch(error){return {ok:false,code:error.code||'AGENT_APPLY_FAILED',message:error.message,results};}
  });
  ipcMain.handle('wa:confirm-cycle', async (e,id,decision='approve') => trusted(e) ? engine.confirm(id,decision) : deny());
  ipcMain.handle('wa:undo-cycle', async (e,id) => trusted(e) ? engine.rollback(id) : deny());
  ipcMain.handle('wa:show-item', async (e,p) => trusted(e) ? (shell.showItemInFolder(path.resolve(p)),{ok:true}) : deny());
  ipcMain.handle('wa:open-path', async (e,p) => {if(!trusted(e))return deny();const target=path.resolve(String(p||''));let st=null;try{st=fs.lstatSync(target);}catch{return{ok:false,code:'OPEN_PATH_NOT_FOUND'}};if(!st.isDirectory())return{ok:false,code:'OPEN_PATH_DIRECTORY_ONLY',message:'Open Path فقط برای پوشه‌ها مجاز است؛ فایل‌ها فقط با Reveal نمایش داده می‌شوند.'};return{ok:(await shell.openPath(target))===''};});

  ipcMain.handle('wa:review-list', (e,root='') => trusted(e) ? reviewQueueStore.list({root}) : deny());
  ipcMain.handle('wa:review-update', (e,id,patch={}) => trusted(e) ? {ok:true,item:reviewQueueStore.update(id,patch)} : deny());
  ipcMain.handle('wa:review-clear', (e,root='') => trusted(e) ? {ok:true,removed:reviewQueueStore.clear(root)} : deny());
  ipcMain.handle('wa:zones-list', e => trusted(e) ? managedZoneStore.list() : deny());
  ipcMain.handle('wa:zones-add', (e,input={}) => {if(!trusted(e))return deny();try{return{ok:true,zone:managedZoneStore.add(input)}}catch(error){return{ok:false,code:error.code||'ZONE_ADD_FAILED',message:error.message}}});
  ipcMain.handle('wa:zones-remove', (e,id) => trusted(e) ? {ok:managedZoneStore.remove(id)} : deny());
  ipcMain.handle('wa:storage-trend', (e,root='') => trusted(e) ? storageTrendStore.list(root,{limit:180}) : deny());

  ipcMain.handle('wa:journal-list', (e,filters={}) => trusted(e) ? journal.list(filters) : deny());
  ipcMain.handle('wa:journal-verify', e => trusted(e) ? journal.verify() : deny());
  ipcMain.handle('wa:recovery-list', e => trusted(e) ? recoveryService.inspect() : deny());
  ipcMain.handle('wa:recovery-act', async (e,id,action) => trusted(e) ? recoveryService.act(id,action) : deny());
  ipcMain.handle('wa:resilience-status', e => trusted(e) ? (rootResilienceService?rootResilienceService.status():{schemaVersion:'root-resilience-v2',running:false,roots:[]}) : deny());
  ipcMain.handle('wa:resilience-probe', async e => trusted(e) ? (rootResilienceService?rootResilienceService.probeNow():{schemaVersion:'root-resilience-v2',running:false,roots:[]}) : deny());
  ipcMain.handle('wa:cert-status', e => trusted(e) ? ({schemaVersion:'workspace-agent-cert-runtime-v2',at:new Date().toISOString(),platform:process.platform,arch:process.arch,node:process.versions.node,electron:process.versions.electron||null,lifecycle:lifecycleState?.status?.()||null,resourcePressure:resourcePressureGuard?.snapshot?.()||null,indexHealth:persistentFileIndex?.health?.({deep:false})||{ok:false,code:'INDEX_SQLITE_UNAVAILABLE'},rootResilience:rootResilienceService?.status?.()||null,watcher:watcherService?.status?.()||null,journal:journal.verify(),localAI:localAIService?.status?.()||null,uiGrounding:uiGroundingService?.status?.()||null,explorerConcurrency:explorerOperationCoordinator?.status?.()||null,updateGuard:updateGuard?.status?.()||null,rcSelfCheck:rcSelfCheckService?.run?.({deepIndex:false})||null}) : deny());
  ipcMain.handle('wa:rc-self-check', (e,deep=false) => {if(!trusted(e))return deny();try{const report=rcSelfCheckService?.run?.({deepIndex:Boolean(deep)})||{schemaVersion:'workspace-agent-rc-selfcheck-v1',overall:'block',summary:{pass:0,warn:0,block:1},checks:[{id:'service',status:'block',code:'SELF_CHECK_UNAVAILABLE'}]};updateGuard?.recordSelfCheck?.(report);return report;}catch(error){return{ok:false,code:error.code||'RC_SELF_CHECK_FAILED',message:error.message}}});
  ipcMain.handle('wa:update-guard-status', e => trusted(e) ? (updateGuard?.status?.()||{schemaVersion:'workspace-agent-update-guard-v1',writeBlocked:false}) : deny());
  ipcMain.handle('wa:diagnostics-export', async e => {if(!trusted(e))return deny();if(!diagnosticsBundleService)return{ok:false,code:'DIAGNOSTICS_UNAVAILABLE'};const r=await dialog.showSaveDialog({title:'Export Redacted Diagnostics',defaultPath:`workspace-agent-diagnostics-${Date.now()}.json.gz`,filters:[{name:'Gzip JSON',extensions:['gz']}]});if(r.canceled||!r.filePath)return{ok:false,cancelled:true};try{return diagnosticsBundleService.saveTo(r.filePath)}catch(error){return{ok:false,code:error.code||'DIAGNOSTICS_EXPORT_FAILED',message:error.message}}});
  ipcMain.handle('wa:state-backup-create', e => {if(!trusted(e))return deny();try{return stateBackupService?.create?.({reason:'manual'})||{ok:false,code:'STATE_BACKUP_UNAVAILABLE'}}catch(error){return{ok:false,code:error.code||'STATE_BACKUP_FAILED',message:error.message}}});
  ipcMain.handle('wa:state-backup-list', e => trusted(e) ? (stateBackupService?.list?.({limit:30})||[]) : deny());
  ipcMain.handle('wa:state-backup-restore-preview', async e => {if(!trusted(e))return deny();if(!stateBackupService)return{ok:false,code:'STATE_BACKUP_UNAVAILABLE'};const r=await dialog.showOpenDialog({title:'Restore Workspace Agent State Backup',properties:['openFile'],filters:[{name:'Workspace Agent Backup',extensions:['gz']}]});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true};try{const preview=stateBackupService.preview(r.filePaths[0]);pruneExpiringTokens(backupRestoreTokens);const token=`backup-${Date.now()}-${crypto.randomBytes(12).toString('hex')}`;backupRestoreTokens.set(token,{file:r.filePaths[0],expiresAt:Date.now()+10*60*1000});return{...preview,token,bundle:undefined};}catch(error){return{ok:false,code:error.code||'STATE_BACKUP_PREVIEW_FAILED',message:error.message}}});
  ipcMain.handle('wa:state-backup-restore-apply', (e,token) => {if(!trusted(e))return deny();pruneExpiringTokens(backupRestoreTokens);const rec=backupRestoreTokens.get(String(token||''));backupRestoreTokens.delete(String(token||''));if(!rec||rec.expiresAt<=Date.now())return{ok:false,code:'STATE_BACKUP_TOKEN_INVALID'};try{return stateBackupService.restore(rec.file,{createPreRestore:true})}catch(error){return{ok:false,code:error.code||'STATE_BACKUP_RESTORE_FAILED',message:error.message}}});
  ipcMain.handle('wa:resource-pressure', e => trusted(e) ? (resourcePressureGuard?.snapshot?.()||{schemaVersion:'resource-pressure-v1',state:'unavailable'}) : deny());
  ipcMain.handle('wa:watch-list', e => trusted(e) ? watcherService.configs() : deny());
  ipcMain.handle('wa:watch-events', (e,limit=300) => trusted(e) ? watcherService.events(limit) : deny());
  ipcMain.handle('wa:watch-status', e => trusted(e) ? watcherService.status() : deny());
  ipcMain.handle('wa:watch-add', (e,root,title='') => {if(!trusted(e))return deny();try{return{ok:true,watch:watcherService.add(root,{title})}}catch(error){return{ok:false,code:error.code||'WATCH_ADD_FAILED',message:error.message}}});
  ipcMain.handle('wa:watch-remove', (e,id) => trusted(e) ? {ok:watcherService.remove(id)} : deny());
  ipcMain.handle('wa:config-export', async e => {if(!trusted(e))return deny();const r=await dialog.showSaveDialog({title:'Export Workspace Agent Settings',defaultPath:'workspace-agent-settings.json',filters:[{name:'JSON',extensions:['json']}]});if(r.canceled||!r.filePath)return{ok:false,cancelled:true};const bundle=await configurationService.saveTo(r.filePath);return{ok:true,filePath:r.filePath,summary:{rules:bundle.automationRules.length,zones:bundle.managedZones.length,watches:bundle.watchRoots.length}};});
  ipcMain.handle('wa:config-import-preview', async e => {if(!trusted(e))return deny();const r=await dialog.showOpenDialog({title:'Import Workspace Agent Settings',properties:['openFile'],filters:[{name:'JSON',extensions:['json']}]});if(r.canceled||!r.filePaths[0])return{ok:false,cancelled:true};try{const preview=await configurationService.previewFile(r.filePaths[0]);pruneExpiringTokens(importTokens);const token=`cfg-${Date.now()}-${crypto.randomBytes(12).toString('hex')}`;importTokens.set(token,{bundle:preview.bundle,expiresAt:Date.now()+10*60*1000});return{ok:true,token,expiresAt:new Date(Date.now()+10*60*1000).toISOString(),summary:{rules:preview.rules,zones:preview.zones,watches:preview.watches}};}catch(error){return{ok:false,code:error.code||'CONFIG_IMPORT_FAILED',message:error.message}}});
  ipcMain.handle('wa:config-import-apply', (e,token) => {if(!trusted(e))return deny();pruneExpiringTokens(importTokens);const rec=importTokens.get(String(token||''));importTokens.delete(String(token||''));if(!rec||rec.expiresAt<=Date.now())return{ok:false,code:'CONFIG_IMPORT_TOKEN_INVALID'};try{return{ok:true,report:configurationService.apply(rec.bundle)}}catch(error){return{ok:false,code:error.code||'CONFIG_APPLY_FAILED',message:error.message}}});

  ipcMain.handle('wa:automation-list', e => trusted(e) ? automationStore.list() : deny());
  ipcMain.handle('wa:automation-status', e => trusted(e) ? automationService.status() : deny());
  ipcMain.handle('wa:automation-create', (e,input={}) => {if(!trusted(e))return deny();try{return{ok:true,rule:automationStore.create(input)}}catch(error){return{ok:false,code:error.code||'AUTOMATION_CREATE_FAILED',message:error.message}}});
  ipcMain.handle('wa:automation-update', (e,id,patch={}) => trusted(e) ? {ok:true,rule:automationStore.update(id,patch)} : deny());
  ipcMain.handle('wa:automation-remove', (e,id) => trusted(e) ? {ok:automationStore.remove(id)} : deny());
  ipcMain.handle('wa:automation-run', async (e,id) => trusted(e) ? automationService.runRule(id,{manual:true}) : deny());
}
module.exports = { registerIpc };
