import React from 'react';
const fa={created:'ساخته شد',running:'در حال اجرا','waiting-confirmation':'منتظر تأیید',completed:'تمام',failed:'خطا',cancelled:'لغو',paused:'مکث امن','rolled-back':'برگشت داده شد','rollback-failed':'برگشت ناقص',pending:'در صف',approved:'تأیید شد'};
const bytes=n=>{if(!n)return'۰ B';const u=['B','KB','MB','GB','TB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(v)} ${u[i]}`};
export default function CycleTimeline({cycle,onConfirm,onUndo,onResume,onCancel,onPauseAuto,autoRunning=false}){
  if(!cycle)return <div className="empty">هنوز چرخه‌ای اجرا نشده.</div>;
  const batch=['explorer-batch-copy','explorer-batch-move'].includes(cycle.type);const undoable=['organize','duplicate-review','maintenance-cleanup','rename','mission','explorer-batch-copy','explorer-batch-move'].includes(cycle.type);const canUndo=(cycle.status==='completed'||cycle.status==='rollback-failed'||(batch&&['cancelled','failed','interrupted'].includes(cycle.status)))&&undoable;
  const previewOps=(cycle.operations||[]).slice(0,10);
  return <div className="cycle-card">
    <div className="cycle-head"><div><b>{cycle.type}</b><small>{cycle.id}</small></div><span className={`badge ${cycle.status}`}>{fa[cycle.status]||cycle.status}</span></div>
    <div className="timeline">{(cycle.steps||[]).map((s,i)=><div className="step" key={`${s.id}-${i}`}><span className={`dot ${s.status}`}>{i+1}</span><div><b>{s.label}</b><small>{s.detail||fa[s.status]||s.status}</small></div></div>)}</div>
    {cycle.status==='waiting-confirmation'&&cycle.type==='duplicate-review'&&<div className="preview-box"><b>Preview قرنطینه Duplicate</b><p>{cycle.review?.length||0} گروه · {cycle.operations?.length||0} فایل · {bytes(cycle.reclaimableBytes)} قابل بازیابی</p>{(cycle.review||[]).slice(0,6).map(r=><div className="preview-row" key={r.groupId}><span><strong>KEEP</strong>{r.keeper?.path}</span><small>{r.quarantined?.length||0} نسخه → Quarantine</small></div>)}</div>}
    {cycle.status==='waiting-confirmation'&&['organize','maintenance-cleanup','rename'].includes(cycle.type)&&<div className="preview-box"><b>Preview عملیات</b><p>{cycle.operations?.length||0} عملیات؛ قبل از Write دوباره وضعیت منبع بررسی می‌شود.</p>{previewOps.map((op,i)=><div className="preview-row" key={`${op.source}-${i}`}><span>{op.source}</span><small>→ {op.destination||op.relativePath||op.newName||op.kind}</small></div>)}</div>}
    {cycle.status==='waiting-confirmation'&&cycle.type==='mission'&&<div className="preview-box"><b>Mission Guard</b><p>یک چرخه فرزند به عملیات Write رسیده است. تأیید شما فقط همان گام را آزاد می‌کند.</p><small>{cycle.pendingChildId}</small></div>}
    {cycle.goalPlan&&<div className="preview-box"><b>Goal Plan</b><p>{cycle.goalPlan.summary}</p>{(cycle.goalPlan.steps||[]).map(s=><div className="preview-row" key={s.id}><span>{s.label}</span><small>{s.type} · {s.requiresConfirmation?'Confirm required':'Read-only'}</small></div>)}</div>}
    {cycle.status==='waiting-confirmation'&&<div className="actions"><button className="primary" onClick={()=>onConfirm(cycle.id,'approve')}>تأیید همین گام و اجرا</button><button onClick={()=>onConfirm(cycle.id,'reject')}>لغو</button></div>}
    {cycle.status==='paused'&&batch&&<div className="actions">{autoRunning?<><button className="primary" onClick={()=>onPauseAuto?.(cycle.id)}>مکث پس از Chunk جاری</button><button onClick={()=>onCancel?.(cycle.id)}>لغو امن پس از Chunk جاری</button></>:<><button className="primary" onClick={()=>onResume?.(cycle.id)}>ادامه خودکار از Checkpoint</button><button onClick={()=>onCancel?.(cycle.id)}>لغو امن Batch</button></>}</div>}
    {batch&&cycle.batchProgress&&<div className="preview-box"><b>Batch Progress{autoRunning?' · Auto Continue':''}</b><p>{cycle.batchProgress.doneItems+cycle.batchProgress.skippedItems} / {cycle.batchProgress.totalItems} · skipped {cycle.batchProgress.skippedItems} · failed {cycle.batchProgress.failedItems}</p><small>{cycle.batchProgress.doneBytes||0} / {cycle.batchProgress.totalBytes||0} bytes{autoRunning?' · checkpointها خودکار ادامه پیدا می‌کنند':''}</small></div>}
    {canUndo&&<button className="danger ghost" onClick={()=>onUndo(cycle.id)}>{cycle.status==='rollback-failed'?'Retry Restore / Undo':'Restore / Undo این چرخه'}</button>}
    {cycle.end&&<div className="endbox"><div className="end-title"><b>پایان چرخه</b><span className={`quality ${cycle.end.quality}`}>{cycle.end.quality||cycle.end.status}</span></div><span>{cycle.end.summary}</span><small>Evidence: {cycle.end.evidenceCount||0} · Steps OK: {cycle.end.completedSteps||0}</small>{cycle.end.nextCycleSuggestions?.length>0&&<small>پیشنهاد چرخه بعد: {cycle.end.nextCycleSuggestions.join(' · ')}</small>}</div>}
  </div>;
}
