const {atomicWriteJsonSync}=require('./durable-state.cjs');
const fs=require('fs');const path=require('path');const crypto=require('crypto');const {normalizeCondition}=require('./automation-conditions.cjs');
function atomic(file,value){return atomicWriteJsonSync(file,value);}
function id(){return`rule-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;}
const ALLOWED_TYPES=new Set(['workspace-health','duplicates','snapshot','snapshot-diff']);
class AutomationStore{
 constructor(baseDir,{maxRules=100}={}){this.dir=path.join(baseDir,'automation');this.file=path.join(this.dir,'rules.json');this.maxRules=Math.max(1,Math.min(500,Number(maxRules)||100));fs.mkdirSync(this.dir,{recursive:true});}
 list(){try{const v=JSON.parse(fs.readFileSync(this.file,'utf8'));return Array.isArray(v)?v:[];}catch{return[];}}
 save(rows){if(rows.length>this.maxRules)throw Object.assign(new Error(`حداکثر ${this.maxRules} Automation Rule قابل نگهداری است؛ Rule قدیمی خودکار حذف نمی‌شود.`),{code:'AUTOMATION_RULE_LIMIT_REACHED',details:{maxRules:this.maxRules}});atomic(this.file,rows);return rows;}
 create(input={}){const type=String(input.cycleType||'workspace-health');if(!ALLOWED_TYPES.has(type))throw Object.assign(new Error('فقط چرخه‌های Read-only/Agent-local برای Automation مجازند.'),{code:'AUTOMATION_TYPE_BLOCKED'});const minutes=Math.max(5,Math.min(10080,Number(input.intervalMinutes||60)));const root=path.resolve(String(input.root||''));if(!input.root)throw Object.assign(new Error('Workspace برای Rule لازم است.'),{code:'ROOT_REQUIRED'});const row={id:id(),title:String(input.title||type).slice(0,100),root,cycleType:type,input:input.input&&typeof input.input==='object'?input.input:{},condition:normalizeCondition(input.condition||{}),intervalMinutes:minutes,enabled:input.enabled!==false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastEvaluatedAt:null,lastCondition:null,lastStartedAt:null,lastFinishedAt:null,lastStatus:null,lastCycleId:null};const rows=[row,...this.list()];this.save(rows);return row;}
 normalizeExactRows(rows){if(!Array.isArray(rows))throw Object.assign(new Error('Automation rows باید آرایه باشد.'),{code:'AUTOMATION_RESTORE_INVALID'});if(rows.length>this.maxRules)throw Object.assign(new Error(`تعداد Ruleهای Backup از سقف ${this.maxRules} بیشتر است.`),{code:'AUTOMATION_RULE_LIMIT_REACHED'});const seen=new Set();return rows.map((r,i)=>{const type=String(r?.cycleType||'');if(!ALLOWED_TYPES.has(type))throw Object.assign(new Error('Cycle type موجود در Backup مجاز نیست.'),{code:'AUTOMATION_TYPE_BLOCKED',details:{index:i,type}});const root=path.resolve(String(r?.root||''));if(!r?.root)throw Object.assign(new Error('Root مربوط به Automation در Backup خالی است.'),{code:'ROOT_REQUIRED',details:{index:i}});const rid=String(r?.id||'');if(!rid||seen.has(rid))throw Object.assign(new Error('Automation id در Backup خالی/تکراری است.'),{code:'AUTOMATION_RESTORE_INVALID',details:{index:i,id:rid}});seen.add(rid);return{...r,id:rid,title:String(r.title||type).slice(0,100),root,cycleType:type,input:r.input&&typeof r.input==='object'?r.input:{},condition:normalizeCondition(r.condition||{}),intervalMinutes:Math.max(5,Math.min(10080,Number(r.intervalMinutes||60))),enabled:r.enabled!==false};});}
 replaceExact(rows){const next=this.normalizeExactRows(rows);this.save(next);return this.list();}
 update(ruleId,patch={}){const rows=this.list();const i=rows.findIndex(r=>r.id===ruleId);if(i<0)return null;const next={...rows[i]};if('enabled'in patch)next.enabled=Boolean(patch.enabled);if('title'in patch)next.title=String(patch.title||next.title).slice(0,100);if('intervalMinutes'in patch)next.intervalMinutes=Math.max(5,Math.min(10080,Number(patch.intervalMinutes||next.intervalMinutes)));if('condition'in patch)next.condition=normalizeCondition(patch.condition||{});next.updatedAt=new Date().toISOString();rows[i]=next;this.save(rows);return next;}
 remove(ruleId){const rows=this.list();const next=rows.filter(r=>r.id!==ruleId);this.save(next);return next.length!==rows.length;}
 record(ruleId,patch={}){const rows=this.list();const i=rows.findIndex(r=>r.id===ruleId);if(i<0)return null;rows[i]={...rows[i],...patch,updatedAt:new Date().toISOString()};this.save(rows);return rows[i];}
}
module.exports={AutomationStore,ALLOWED_TYPES};
