const {evaluateCondition}=require('./automation-conditions.cjs');
class AutomationService{
 constructor({engine,ruleStore,onResult=null,tickMs=60000}={}){this.engine=engine;this.ruleStore=ruleStore;this.onResult=onResult;this.tickMs=tickMs;this.timer=null;this.running=new Set();this.hostContract='foreground-gui-v1';}
 start(){if(this.timer)return;this.timer=setInterval(()=>this.tick().catch(()=>{}),this.tickMs);this.timer.unref?.();setTimeout(()=>this.tick().catch(()=>{}),2500).unref?.();}
 stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
 status(){return{schemaVersion:'workspace-automation-host-v1',hostContract:this.hostContract,backgroundService:false,startWithWindows:false,running:Boolean(this.timer),activeRules:this.running.size};}
 due(rule,nowMs=Date.now()){if(!rule.enabled)return false;const base=rule.lastEvaluatedAt||rule.lastStartedAt;if(!base)return true;const last=Date.parse(base);return !Number.isFinite(last)||nowMs-last>=Number(rule.intervalMinutes||60)*60000;}
 async runRule(ruleId,{manual=false}={}){const rule=this.ruleStore.list().find(r=>r.id===ruleId);if(!rule)return{ok:false,code:'RULE_NOT_FOUND'};if(this.running.has(rule.id))return{ok:false,code:'RULE_ALREADY_RUNNING'};this.running.add(rule.id);const evaluatedAt=new Date().toISOString();try{const condition=await evaluateCondition(rule);this.ruleStore.record(rule.id,{lastEvaluatedAt:evaluatedAt,lastCondition:condition,lastStatus:condition.met?'condition-met':'condition-not-met'});if(!condition.met)return{ok:true,skipped:true,conditionMet:false,condition,rule:this.ruleStore.list().find(r=>r.id===rule.id)};const startedAt=new Date().toISOString();this.ruleStore.record(rule.id,{lastStartedAt:startedAt,lastStatus:'running'});const c=this.engine.create(rule.cycleType,{root:rule.root,...(rule.input||{})},{automationRuleId:rule.id,manualAutomationRun:manual,condition});const done=await this.engine.run(c.id);this.ruleStore.record(rule.id,{lastFinishedAt:new Date().toISOString(),lastStatus:done.status,lastCycleId:done.id});try{await this.onResult?.(rule,done);}catch{}return{ok:done.status==='completed',conditionMet:true,condition,rule:this.ruleStore.list().find(r=>r.id===rule.id),cycle:done};}catch(error){this.ruleStore.record(rule.id,{lastFinishedAt:new Date().toISOString(),lastStatus:'failed'});return{ok:false,code:error.code||'AUTOMATION_FAILED',message:error.message};}finally{this.running.delete(rule.id);}}
 async tick(){const now=Date.now();for(const rule of this.ruleStore.list()){if(this.due(rule,now)&&!this.running.has(rule.id))await this.runRule(rule.id);}}
}
module.exports={AutomationService};
