const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const {atomicWriteJson}=require('./durable-state.cjs');
class ConfigurationService{
 constructor({automationStore,managedZoneStore,watcherService,journal=null}={}){this.automationStore=automationStore;this.managedZoneStore=managedZoneStore;this.watcherService=watcherService;this.journal=journal;}
 exportBundle(){return{schemaVersion:'workspace-agent-config-v1',exportedAt:new Date().toISOString(),automationRules:this.automationStore?.list()||[],managedZones:this.managedZoneStore?.list()||[],watchRoots:this.watcherService?.configs()||[],policy:{workspaceFilesIncluded:false,secretsIncluded:false}};}
 async saveTo(file){const bundle=this.exportBundle();await atomicWriteJson(file,bundle);this.journal?.append('CONFIG_EXPORTED',{payload:{file:path.basename(file),rules:bundle.automationRules.length,zones:bundle.managedZones.length,watches:bundle.watchRoots.length}});return bundle;}
 async previewFile(file){const v=JSON.parse(await fsp.readFile(file,'utf8'));if(v?.schemaVersion!=='workspace-agent-config-v1')throw Object.assign(new Error('نسخه فایل تنظیمات پشتیبانی نمی‌شود.'),{code:'CONFIG_SCHEMA_UNSUPPORTED'});return{schemaVersion:v.schemaVersion,rules:Array.isArray(v.automationRules)?v.automationRules.length:0,zones:Array.isArray(v.managedZones)?v.managedZones.length:0,watches:Array.isArray(v.watchRoots)?v.watchRoots.length:0,bundle:v};}
 validateExact(bundle){if(bundle?.schemaVersion!=='workspace-agent-config-v1')throw Object.assign(new Error('Config schema نامعتبر است.'),{code:'CONFIG_SCHEMA_UNSUPPORTED'});const rules=this.automationStore?.normalizeExactRows?this.automationStore.normalizeExactRows(bundle.automationRules||[]):bundle.automationRules||[];const zones=this.managedZoneStore?.normalizeExactRows?this.managedZoneStore.normalizeExactRows(bundle.managedZones||[]):bundle.managedZones||[];const watches=this.watcherService?.normalizeExactRows?this.watcherService.normalizeExactRows(bundle.watchRoots||[]):bundle.watchRoots||[];return{schemaVersion:'workspace-agent-config-v1',exportedAt:String(bundle.exportedAt||new Date().toISOString()),automationRules:rules,managedZones:zones,watchRoots:watches,policy:{workspaceFilesIncluded:false,secretsIncluded:false}};}
 replaceExact(bundle,{emitJournal=true}={}){const target=this.validateExact(bundle),previous=this.exportBundle();let stage='validated';try{this.automationStore?.replaceExact?.(target.automationRules||[]);stage='automation';this.managedZoneStore?.replaceExact?.(target.managedZones||[]);stage='zones';this.watcherService?.replaceExact?.(target.watchRoots||[]);stage='watches';const report={mode:'exact-replacement',rules:target.automationRules.length,zones:target.managedZones.length,watches:target.watchRoots.length};if(emitJournal)this.journal?.append('CONFIG_RESTORED_EXACT',{payload:report});return report;}catch(error){let rollbackError=null;try{this.automationStore?.replaceExact?.(previous.automationRules||[]);this.managedZoneStore?.replaceExact?.(previous.managedZones||[]);this.watcherService?.replaceExact?.(previous.watchRoots||[]);}catch(rb){rollbackError=rb;}if(rollbackError)throw Object.assign(new Error('Exact config restore و rollback هر دو ناموفق شدند.'),{code:'CONFIG_RESTORE_ROLLBACK_FAILED',details:{stage,cause:error.code||error.message,rollbackCause:rollbackError.code||rollbackError.message}});throw Object.assign(new Error('Exact config restore ناموفق بود و state قبلی بازگردانی شد.'),{code:'CONFIG_RESTORE_FAILED',details:{stage,cause:error.code||error.message}});}}
 apply(bundle){if(bundle?.schemaVersion!=='workspace-agent-config-v1')throw Object.assign(new Error('Config schema نامعتبر است.'),{code:'CONFIG_SCHEMA_UNSUPPORTED'});const report={rules:{added:0,skipped:0},zones:{added:0,skipped:0},watches:{added:0,skipped:0}};for(const r of bundle.automationRules||[]){try{const exists=this.automationStore.list().some(x=>x.root===path.resolve(r.root)&&x.cycleType===r.cycleType&&x.title===r.title);if(exists){report.rules.skipped++;continue;}this.automationStore.create({title:r.title,root:r.root,cycleType:r.cycleType,input:r.input,condition:r.condition,intervalMinutes:r.intervalMinutes,enabled:r.enabled});report.rules.added++;}catch{report.rules.skipped++;}}
   for(const z of bundle.managedZones||[]){try{const exists=this.managedZoneStore.list().some(x=>path.resolve(x.root)===path.resolve(z.root));if(exists){report.zones.skipped++;continue;}this.managedZoneStore.add({title:z.title,root:z.root,type:z.type});report.zones.added++;}catch{report.zones.skipped++;}}
   for(const w of bundle.watchRoots||[]){try{const exists=this.watcherService.configs().some(x=>path.resolve(x.root)===path.resolve(w.root));if(exists){report.watches.skipped++;continue;}this.watcherService.add(w.root,{title:w.title});report.watches.added++;}catch{report.watches.skipped++;}}
   this.journal?.append('CONFIG_IMPORTED',{payload:report});return report;}
}
module.exports={ConfigurationService};
