const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {appendLineDurableSync,syncDirBestEffort,atomicWriteJsonSync}=require('./durable-state.cjs');
function stable(v){try{return JSON.stringify(v);}catch{return JSON.stringify({unserializable:true});}}
function safePayload(payload,maxChars=24000){const raw=stable(payload??{});if(raw.length<=maxChars)return JSON.parse(raw);return{truncated:true,preview:raw.slice(0,maxChars),originalChars:raw.length};}
function eventHash(e){return crypto.createHash('sha256').update(stable({seq:e.seq,at:e.at,type:e.type,cycleId:e.cycleId||null,transactionId:e.transactionId||null,payload:e.payload,prevHash:e.prevHash})).digest('hex');}
function anchorHash(a){const c={...a};delete c.anchorHash;return crypto.createHash('sha256').update(stable(c)).digest('hex');}
function validArchiveName(name=''){return/^events-.+\.ndjson$/i.test(String(name||''))&&!String(name).includes('/')&&!String(name).includes('\\');}
class EventJournal{
  constructor(baseDir,{maxBytes=25*1024*1024,maxArchiveFiles=64,maxArchiveBytes=512*1024*1024,minArchives=1,pressureFreeBytes=2*1024*1024*1024,pressureArchiveFiles=8,pressureArchiveBytes=128*1024*1024,freeBytesProvider=null}={}){
    this.dir=path.join(baseDir,'journal');this.file=path.join(this.dir,'events.ndjson');this.anchorFile=path.join(this.dir,'retention-anchor.json');this.retentionIntentFile=path.join(this.dir,'retention-intent.json');this.maxBytes=maxBytes;this.maxArchiveFiles=Math.max(1,Number(maxArchiveFiles)||64);this.maxArchiveBytes=Math.max(maxBytes,Number(maxArchiveBytes)||512*1024*1024);this.minArchives=Math.max(1,Number(minArchives)||1);this.pressureFreeBytes=Math.max(0,Number(pressureFreeBytes)||0);this.pressureArchiveFiles=Math.max(this.minArchives,Number(pressureArchiveFiles)||8);this.pressureArchiveBytes=Math.max(maxBytes,Number(pressureArchiveBytes)||128*1024*1024);this.freeBytesProvider=freeBytesProvider||(()=>{try{const s=fs.statfsSync(this.dir,{bigint:true});return Number(s.bavail*s.bsize);}catch{return Number.POSITIVE_INFINITY;}});fs.mkdirSync(this.dir,{recursive:true});this.retentionRecovery=this._recoverRetentionIntent();this.recovery=this._repairTornActiveTail();const tail=this._scanAll({allowLegacySegments:true});this.seq=tail.seq;this.lastHash=tail.lastHash;this.continuity=tail.continuity;if(this.recovery?.repaired){this.append('JOURNAL_TORN_TAIL_RECOVERED',{payload:{discardedBytes:this.recovery.discardedBytes}});}}
  _readAnchor(){try{const a=JSON.parse(fs.readFileSync(this.anchorFile,'utf8'));if(a?.schemaVersion!=='workspace-journal-retention-anchor-v1'||a.anchorHash!==anchorHash(a))return{invalid:true,code:'JOURNAL_RETENTION_ANCHOR_INVALID'};return a;}catch{return null;}}
  _recoverRetentionIntent(){try{if(!fs.existsSync(this.retentionIntentFile))return{recovered:false};const i=JSON.parse(fs.readFileSync(this.retentionIntentFile,'utf8'));const copy={...i};delete copy.intentHash;const expected=crypto.createHash('sha256').update(stable(copy)).digest('hex');if(i?.schemaVersion!=='workspace-journal-retention-intent-v1'||expected!==i.intentHash||!i.anchor||i.anchor.anchorHash!==anchorHash(i.anchor))return{recovered:false,ok:false,code:'JOURNAL_RETENTION_INTENT_INVALID'};for(const name of i.removeFiles||[]){if(!validArchiveName(name))return{recovered:false,ok:false,code:'JOURNAL_RETENTION_INTENT_PATH_INVALID'};try{fs.unlinkSync(path.join(this.dir,name));}catch(error){if(error?.code!=='ENOENT')throw error;}}atomicWriteJsonSync(this.anchorFile,i.anchor);try{fs.unlinkSync(this.retentionIntentFile);}catch{}syncDirBestEffort(this.dir);return{recovered:true,ok:true,removed:(i.removeFiles||[]).length,anchorHash:i.anchor.anchorHash};}catch(error){return{recovered:false,ok:false,code:'JOURNAL_RETENTION_RECOVERY_FAILED',message:String(error.message||error).slice(0,500)};}}
  _archivedFiles(){let rows=[];try{rows=fs.readdirSync(this.dir).filter(x=>validArchiveName(x)).map(name=>{const file=path.join(this.dir,name);let st=null;try{st=fs.statSync(file)}catch{}return{name,file,mtimeMs:Number(st?.mtimeMs||0),bytes:Number(st?.size||0)};}).filter(x=>x.file!==this.file).sort((a,b)=>a.mtimeMs-b.mtimeMs||a.name.localeCompare(b.name));}catch{}return rows;}
  _allFiles(){return[...this._archivedFiles().map(x=>x.file),this.file].filter(f=>{try{return fs.statSync(f).isFile()}catch{return false}});}
  _repairTornActiveTail(){try{const buf=fs.readFileSync(this.file);if(!buf.length||buf[buf.length-1]===10)return{repaired:false,discardedBytes:0};const lastLf=buf.lastIndexOf(10);const keep=lastLf<0?0:lastLf+1;const discarded=buf.length-keep;fs.truncateSync(this.file,keep);syncDirBestEffort(this.dir);return{repaired:true,discardedBytes:discarded};}catch{return{repaired:false,discardedBytes:0};}}
  _scanAll({allowLegacySegments=false}={}){
    const recoveryProblem=this.retentionRecovery?.ok===false?this.retentionRecovery.code:null;
    const anchorRead=this._readAnchor();
    const anchorProblem=anchorRead?.invalid?anchorRead.code:null;
    const anchor=anchorProblem?null:anchorRead;
    const integrityProblem=recoveryProblem||anchorProblem||null;
    let expected=anchor?.prunedThroughHash||((anchorProblem)?null:'GENESIS');
    let seq=Number(anchor?.prunedThroughSeq||0),count=Number(anchor?.prunedEvents||0),retainedCount=0,segments=0,legacyBreaks=0;
    let countKnown=!anchorProblem;
    for(const file of this._allFiles()){
      let lines=[];try{lines=fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean);}catch{continue;}
      if(!lines.length)continue;segments++;let first=true;
      for(const line of lines){
        let e;try{e=JSON.parse(line);}catch{return{ok:false,seq,lastHash:expected||'GENESIS',count,countKnown,retainedCount,segments,legacyBreaks,invalidFile:path.basename(file),code:'JOURNAL_JSON_INVALID',continuity:legacyBreaks?'legacy-segmented':(integrityProblem?'unknown':'full')};}
        if(expected===null){
          expected=String(e.prevHash||'GENESIS');
          seq=Math.max(0,(Number(e.seq)||1)-1);
          count=0;
        }else if(first&&allowLegacySegments&&!anchor&&!anchorProblem&&!integrityProblem&&count>0&&e.prevHash==='GENESIS'&&expected!=='GENESIS'){
          legacyBreaks+=1;expected='GENESIS';seq=0;
        }
        first=false;
        const hash=eventHash(e);
        if(e.prevHash!==expected||e.hash!==hash)return{ok:false,seq,lastHash:expected||'GENESIS',count,countKnown,retainedCount,segments,legacyBreaks,invalidSeq:e.seq||null,invalidFile:path.basename(file),code:'JOURNAL_CHAIN_INVALID',continuity:legacyBreaks?'legacy-segmented':(integrityProblem?'unknown':'full')};
        expected=e.hash;seq=Number(e.seq)||seq;count++;retainedCount++;
      }
    }
    const base={seq,lastHash:expected||'GENESIS',count,countKnown,retainedCount,segments,legacyBreaks,continuity:legacyBreaks?'legacy-segmented':(integrityProblem?'unknown':'full'),anchor:anchor?{prunedThroughSeq:anchor.prunedThroughSeq,prunedEvents:anchor.prunedEvents,prunedSegments:anchor.prunedSegments,prunedBytes:anchor.prunedBytes,anchorHash:anchor.anchorHash}:null};
    if(integrityProblem)return{...base,ok:false,code:integrityProblem,internalRetainedChainOk:true};
    return{...base,ok:true};
  }
  _segmentSummary(file){let first=null,last=null,count=0;const lines=fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean);for(const line of lines){const e=JSON.parse(line);if(!first)first=e;last=e;count++;}return{first,last,count,bytes:fs.statSync(file).size};}
  _retentionPolicy(){let freeBytes=Number.POSITIVE_INFINITY;try{freeBytes=Number(this.freeBytesProvider());}catch{}const pressure=Number.isFinite(freeBytes)&&freeBytes<this.pressureFreeBytes;return{pressure,freeBytes,maxArchiveFiles:pressure?Math.min(this.maxArchiveFiles,this.pressureArchiveFiles):this.maxArchiveFiles,maxArchiveBytes:pressure?Math.min(this.maxArchiveBytes,this.pressureArchiveBytes):this.maxArchiveBytes,minArchives:this.minArchives};}
  _enforceRetention(){const archives=this._archivedFiles();const policy=this._retentionPolicy();let bytes=archives.reduce((a,x)=>a+x.bytes,0);if(archives.length<=policy.maxArchiveFiles&&bytes<=policy.maxArchiveBytes)return null;const verified=this._scanAll({allowLegacySegments:true});if(!verified.ok||verified.continuity!=='full')return{ok:false,code:!verified.ok?verified.code:'JOURNAL_RETENTION_REQUIRES_FULL_CHAIN'};const remove=[],remain=[...archives];while(remain.length>policy.minArchives&&(remain.length>policy.maxArchiveFiles||bytes>policy.maxArchiveBytes)){const x=remain.shift();remove.push(x);bytes-=x.bytes;}if(!remove.length)return null;let removedEvents=0,removedBytes=0,lastEvent=null;for(const x of remove){const s=this._segmentSummary(x.file);removedEvents+=s.count;removedBytes+=s.bytes;lastEvent=s.last;}if(!lastEvent)return null;const old=this._readAnchor();if(old?.invalid)return{ok:false,code:old.code};const anchor={schemaVersion:'workspace-journal-retention-anchor-v1',createdAt:new Date().toISOString(),prunedThroughSeq:Number(lastEvent.seq)||0,prunedThroughHash:String(lastEvent.hash||''),prunedEvents:Number(old?.prunedEvents||0)+removedEvents,prunedSegments:Number(old?.prunedSegments||0)+remove.length,prunedBytes:Number(old?.prunedBytes||0)+removedBytes,previousAnchorHash:old?.anchorHash||'GENESIS',policy:{pressure:policy.pressure,maxArchiveFiles:policy.maxArchiveFiles,maxArchiveBytes:policy.maxArchiveBytes},firstRetainedFile:remain[0]?.name||'events.ndjson'};anchor.anchorHash=anchorHash(anchor);const intent={schemaVersion:'workspace-journal-retention-intent-v1',createdAt:new Date().toISOString(),removeFiles:remove.map(x=>x.name),anchor};intent.intentHash=crypto.createHash('sha256').update(stable(intent)).digest('hex');atomicWriteJsonSync(this.retentionIntentFile,intent);for(const x of remove)fs.unlinkSync(x.file);atomicWriteJsonSync(this.anchorFile,anchor);fs.unlinkSync(this.retentionIntentFile);syncDirBestEffort(this.dir);return{ok:true,removedFiles:remove.length,removedEvents,removedBytes,anchorHash:anchor.anchorHash,pressure:policy.pressure};}
  append(type,{cycleId=null,transactionId=null,payload={}}={}){const retention=this._rotateIfNeeded();if(retention?.ok===false)throw Object.assign(new Error('Journal retention نتوانست زنجیره قابل‌اعتماد را حفظ کند.'),{code:retention.code});const event={seq:this.seq+1,at:new Date().toISOString(),type:String(type||'EVENT'),cycleId,transactionId,payload:safePayload(payload),prevHash:this.lastHash};event.hash=eventHash(event);appendLineDurableSync(this.file,JSON.stringify(event)+'\n');this.seq=event.seq;this.lastHash=event.hash;return event;}
  _rotateIfNeeded(){try{if(fs.statSync(this.file).size<this.maxBytes)return null;const rotated=path.join(this.dir,`events-${String(this.seq).padStart(12,'0')}-${Date.now()}.ndjson`);fs.renameSync(this.file,rotated);syncDirBestEffort(this.dir);return this._enforceRetention();}catch(error){if(error?.code==='ENOENT')return null;return{ok:false,code:error.code||'JOURNAL_ROTATION_FAILED'};}}
  list({limit=300,cycleId='',transactionId='',type=''}={}){const cap=Math.max(1,Math.min(5000,Number(limit||300)));const rows=[];for(const file of this._allFiles()){let lines=[];try{lines=fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean);}catch{}for(const line of lines){let e=null;try{e=JSON.parse(line)}catch{}if(e&&(!cycleId||e.cycleId===cycleId)&&(!transactionId||e.transactionId===transactionId)&&(!type||e.type===type))rows.push(e);}}return rows.slice(-cap).reverse();}
  verify(){const result=this._scanAll({allowLegacySegments:true});const p=this._retentionPolicy();return{...result,recovery:this.recovery,retentionRecovery:this.retentionRecovery,retention:{bounded:true,maxArchiveFiles:p.maxArchiveFiles,maxArchiveBytes:p.maxArchiveBytes,pressure:p.pressure,freeBytes:Number.isFinite(p.freeBytes)?p.freeBytes:null,archiveFiles:this._archivedFiles().length,archiveBytes:this._archivedFiles().reduce((a,x)=>a+x.bytes,0)}};}
}
module.exports={EventJournal,eventHash,anchorHash};
