const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const {hashFile}=require('./duplicate-finder.cjs');
function exists(p){try{return Boolean(p)&&fs.existsSync(p);}catch{return false;}}
function statType(st){if(!st)return'missing';if(st.isFile())return'file';if(st.isDirectory())return'directory';if(st.isSymbolicLink())return'link';return'other';}
function snapshotMatch(st,snap,{allowMtimeDriftMs=2}={}){if(!snap)return true;if(!st||statType(st)!==String(snap.type||''))return false;if(snap.type==='file'&&Number(st.size)!==Number(snap.size))return false;if(Math.abs(Number(st.mtimeMs||0)-Number(snap.mtimeMs||0))>allowMtimeDriftMs)return false;if(Number(snap.dev||0)&&Number(st.dev||0)&&Number(snap.dev)!==Number(st.dev))return false;if(Number(snap.ino||0)&&Number(st.ino||0)&&Number(snap.ino)!==Number(st.ino))return false;return true;}
function pathState(p,op,{matchSnapshot=true}={}){if(!exists(p))return{exists:false,valid:false};try{const st=fs.lstatSync(p);const kind=String(op?.meta?.kind||'');const dir=kind==='quarantine-dir'||kind.endsWith('-dir');const typeOk=dir?st.isDirectory():st.isFile();const sizeOk=dir||Number(st.size)===Number(op.size);const snapshotOk=!matchSnapshot||snapshotMatch(st,op?.meta?.sourceSnapshot||null);return{exists:true,valid:typeOk&&sizeOk&&snapshotOk,typeOk,sizeOk,snapshotOk,size:st.size};}catch{return{exists:true,valid:false};}}
function isCopyOp(op){return String(op?.meta?.kind||'')==='explorer-copy-file';}
async function verifyCopyMatch(source,target){const ss=await fsp.stat(source),ts=await fsp.stat(target);if(!ss.isFile()||!ts.isFile()||Number(ss.size)!==Number(ts.size))return{ok:false,code:'RECOVERY_COPY_SIZE_MISMATCH'};const [a,b]=await Promise.all([hashFile(source),hashFile(target)]);return a===b?{ok:true,sha256:a}:{ok:false,code:'RECOVERY_COPY_CONTENT_MISMATCH',sourceHash:a,targetHash:b};}
async function syncFile(file){const fh=await fsp.open(file,'r+');try{await fh.sync();}finally{await fh.close();}}
function classifyOp(op){const copy=isCopyOp(op);const ss=pathState(op.source,op,{matchSnapshot:true}),gs=op.stage?pathState(op.stage,op,{matchSnapshot:!copy}):{exists:false,valid:false},ds=pathState(op.destination,op,{matchSnapshot:!copy});const s=ss.exists,g=gs.exists,d=ds.exists;
  if(copy){if(s&&!g&&!d&&ss.valid)return{state:'copy-source',safeResume:true,safeRollback:true};if(s&&g&&!d&&ss.valid&&gs.valid)return{state:'copy-staged',safeResume:true,safeRollback:true};if(s&&!g&&d&&ss.valid&&ds.valid)return{state:'copy-destination',safeResume:true,safeRollback:true};if(!s)return{state:'copy-source-missing',safeResume:false,safeRollback:false};return{state:'ambiguous',safeResume:false,safeRollback:false,source:ss,stage:gs,destination:ds};}
  if(s&&!g&&!d&&ss.valid)return{state:'source',safeResume:true,safeRollback:true};if(op.stage&&!s&&g&&!d&&gs.valid)return{state:'staged',safeResume:true,safeRollback:true};if(!s&&!g&&d&&ds.valid)return{state:'destination',safeResume:true,safeRollback:true};if(!s&&!g&&!d)return{state:'missing',safeResume:false,safeRollback:false};return{state:'ambiguous',safeResume:false,safeRollback:false,source:ss,stage:gs,destination:ds};}
class RecoveryService{
 constructor({transactionStore,cycleStore=null,journal=null,onRecovered=null}={}){this.store=transactionStore;this.cycleStore=cycleStore;this.journal=journal;this.onRecovered=onRecovered;}
 inspect(){return this.store.list({recoverableOnly:false}).filter(tx=>!['completed','rolled-back','abandoned'].includes(tx.status)||this.cycleStore?.get(tx.cycleId)?.status==='interrupted').map(tx=>{const ops=tx.operations.map(op=>({...op,recovery:classifyOp(op)}));const ambiguous=ops.filter(x=>!x.recovery.safeResume||!x.recovery.safeRollback);const committed=ops.filter(x=>['destination','copy-destination'].includes(x.recovery.state)).length,staged=ops.filter(x=>['staged','copy-staged'].includes(x.recovery.state)).length,pending=ops.filter(x=>['source','copy-source'].includes(x.recovery.state)).length;return{...tx,operations:ops,recovery:{resumeAllowed:ambiguous.length===0,rollbackAllowed:ambiguous.length===0,manualReview:ambiguous.length>0,committed,staged,pending,ambiguous:ambiguous.length,recommendation:ambiguous.length?'manual-review':tx.status==='completed'?'reconcile-or-rollback':committed>0?'rollback-or-resume':staged>0?'resume-or-rollback':'resume'}};});}
 async act(id,action){const tx=this.store.get(id);if(!tx)return{ok:false,code:'TRANSACTION_NOT_FOUND'};const inspected=this.inspect().find(x=>x.id===id);if(!inspected)return{ok:false,code:'TRANSACTION_NOT_RECOVERABLE'};if(inspected.recovery.manualReview)return{ok:false,code:'RECOVERY_MANUAL_REVIEW_REQUIRED',transaction:inspected};if(!['resume','rollback','abandon'].includes(action))return{ok:false,code:'INVALID_RECOVERY_ACTION'};if(action==='abandon'){this.store.mark(id,{status:'abandoned'});this.journal?.append('RECOVERY_ABANDONED',{cycleId:tx.cycleId,transactionId:id});return{ok:true,action,transaction:this.store.get(id)};}
   this.store.mark(id,{status:`recovery-${action}`});const order=action==='rollback'?[...tx.operations].reverse():tx.operations;
   try{for(const op of order){const state=classifyOp(op).state;if(isCopyOp(op)){
       if(action==='resume'){
         if(state==='copy-source'){if(!op.stage)throw Object.assign(new Error('Copy recovery stage missing'),{code:'RECOVERY_COPY_STAGE_REQUIRED'});await fsp.mkdir(path.dirname(op.stage),{recursive:true});await fsp.copyFile(op.source,op.stage,fs.constants.COPYFILE_EXCL);await syncFile(op.stage);const verified=await verifyCopyMatch(op.source,op.stage);if(!verified.ok)throw Object.assign(new Error('Recovery copy staging با منبع برابر نیست.'),{code:verified.code,details:verified});this.store.markOp(id,op.index,{state:'staged-recovery',recoveryHash:verified.sha256||null});await fsp.mkdir(path.dirname(op.destination),{recursive:true});if(exists(op.destination))throw Object.assign(new Error('Recovery destination occupied'),{code:'RECOVERY_DESTINATION_OCCUPIED'});await fsp.rename(op.stage,op.destination);this.store.markOp(id,op.index,{state:'committed-recovery',recoveryHash:verified.sha256||null});}
         else if(state==='copy-staged'){const verified=await verifyCopyMatch(op.source,op.stage);if(!verified.ok)throw Object.assign(new Error('Recovery staging تغییر کرده و Commit امن نیست.'),{code:verified.code,details:verified});await fsp.mkdir(path.dirname(op.destination),{recursive:true});if(exists(op.destination))throw Object.assign(new Error('Recovery destination occupied'),{code:'RECOVERY_DESTINATION_OCCUPIED'});await fsp.rename(op.stage,op.destination);this.store.markOp(id,op.index,{state:'committed-recovery',recoveryHash:verified.sha256||null});}
         else if(state==='copy-destination'){const verified=await verifyCopyMatch(op.source,op.destination);if(!verified.ok)throw Object.assign(new Error('Copy مقصد بعد از Crash با منبع برابر نیست؛ Recovery خودکار متوقف شد.'),{code:verified.code,details:verified});this.store.markOp(id,op.index,{state:'committed-recovery',recoveryHash:verified.sha256||null});}
       }else{
         if(state==='copy-destination'){const verified=await verifyCopyMatch(op.source,op.destination);if(!verified.ok)throw Object.assign(new Error('Copy مقصد تغییر کرده است؛ برای جلوگیری از حذف داده Rollback متوقف شد.'),{code:verified.code,details:verified});await fsp.rm(op.destination,{force:false});this.store.markOp(id,op.index,{state:'rolled-back-recovery',recoveryHash:verified.sha256||null});}
         else if(state==='copy-staged'){await fsp.rm(op.stage,{force:true});this.store.markOp(id,op.index,{state:'rolled-back-recovery'});}
         else if(state==='copy-source'){this.store.markOp(id,op.index,{state:'rolled-back-recovery'});}
       }
       continue;
     }
     if(action==='resume'){
       if(state==='source'){await fsp.mkdir(path.dirname(op.destination),{recursive:true});if(exists(op.destination))throw Object.assign(new Error('Recovery destination occupied'),{code:'RECOVERY_DESTINATION_OCCUPIED'});if(op.stage){await fsp.mkdir(path.dirname(op.stage),{recursive:true});await fsp.rename(op.source,op.stage);this.store.markOp(id,op.index,{state:'staged-recovery'});await fsp.rename(op.stage,op.destination);}else await fsp.rename(op.source,op.destination);this.store.markOp(id,op.index,{state:'committed-recovery'});}
       else if(state==='staged'){await fsp.mkdir(path.dirname(op.destination),{recursive:true});if(exists(op.destination))throw Object.assign(new Error('Recovery destination occupied'),{code:'RECOVERY_DESTINATION_OCCUPIED'});await fsp.rename(op.stage,op.destination);this.store.markOp(id,op.index,{state:'committed-recovery'});}else if(state==='destination'){this.store.markOp(id,op.index,{state:'committed-recovery'});}
     }else{
       if(state==='destination'){if(exists(op.source))throw Object.assign(new Error('Recovery source occupied'),{code:'RECOVERY_SOURCE_OCCUPIED'});await fsp.mkdir(path.dirname(op.source),{recursive:true});await fsp.rename(op.destination,op.source);this.store.markOp(id,op.index,{state:'rolled-back-recovery'});}
       else if(state==='staged'){if(exists(op.source))throw Object.assign(new Error('Recovery source occupied'),{code:'RECOVERY_SOURCE_OCCUPIED'});await fsp.mkdir(path.dirname(op.source),{recursive:true});await fsp.rename(op.stage,op.source);this.store.markOp(id,op.index,{state:'rolled-back-recovery'});}else if(state==='source'){this.store.markOp(id,op.index,{state:'rolled-back-recovery'});}
     }}this.store.mark(id,{status:action==='resume'?'completed':'rolled-back'});const finalTx=this.store.get(id);try{await this.onRecovered?.(finalTx,action);}catch(error){this.journal?.append('RECOVERY_LOCAL_STATE_WARNING',{cycleId:tx.cycleId,transactionId:id,payload:{action,error:error.code||error.message}});}this.journal?.append('RECOVERY_COMPLETED',{cycleId:tx.cycleId,transactionId:id,payload:{action}});return{ok:true,action,transaction:finalTx};
   }catch(error){this.store.mark(id,{status:'recovery-failed',recoveryError:error.code||error.message});this.journal?.append('RECOVERY_FAILED',{cycleId:tx.cycleId,transactionId:id,payload:{action,error:error.code||error.message}});return{ok:false,action,code:error.code||'RECOVERY_FAILED',message:error.message,transaction:this.store.get(id)};}
 }
}
module.exports={RecoveryService,classifyOp};
